import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import path from 'node:path';const root=process.cwd();const read=(p:string)=>readFileSync(path.join(root,p),'utf8');const sql=read('sql/phase-35-1-configuracion-empresarial-modular.sql');const service=read('src/modules/empresa-configuracion/empresa-configuracion.service.ts');const routes=read('src/modules/empresa-configuracion/empresa-configuracion.routes.ts');const ui=read('FrontendNuevo/src/pages/admin/ConfiguracionGeneral/tabs/EmpresaConfiguracionTab.tsx');
test('1 configuración A y B se separa por empresa_id',()=>{assert.match(sql,/empresa_id BIGINT PRIMARY KEY/);assert.match(service,/WHERE e\.id=\$1/)});
test('2 tenant bloquea acceso cruzado',()=>assert.match(service,/assertTenantAccessForEmpresaId/));
test('3 organización de una empresa usa el mismo modelo',()=>assert.match(service,/JOIN organizaciones/));
test('4 organización multiempresa no comparte configuración',()=>assert.match(sql,/UNIQUE\(empresa_id,modulo_id\)/));
test('5 solo módulos habilitados se devuelven',()=>assert.match(service,/caps\.modulos\[r\.codigo\]/));
test('6 módulo deshabilitado no se configura',()=>assert.match(service,/MODULE_NOT_ENABLED/));
test('7 cambio A B cancela respuesta tardía',()=>{assert.match(ui,/let active=true/);assert.match(ui,/active=false/)});
test('8 configuración general persiste por upsert',()=>assert.match(service,/ON CONFLICT\(empresa_id\) DO UPDATE/));
test('9 parámetro resuelve vigencia por fecha',()=>assert.match(service,/vigente_desde<=\$2::date/));
test('10 históricos no se sobrescriben y no se solapan',()=>{assert.doesNotMatch(service,/UPDATE nomina_parametros_economicos/);assert.match(sql,/ex_nomina_parametros_sin_solape/)});
test('11 legacy reutiliza capabilities',()=>assert.match(service,/getEmpresaCapabilities/));
test('12 SaaS ADMIN-2B no se duplica',()=>assert.match(service,/\.\.\/saas\/saas\.service/));
test('13 identidad existente se preserva en empresas',()=>assert.match(service,/UPDATE empresas SET direccion/));
test('14 Nómina queda preparada sin conectar calculador',()=>{assert.match(sql,/nomina_parametros_economicos/);assert.doesNotMatch(service,/nomina\.calculator/)});
test('15 Cobertura se presenta solo por capability',()=>assert.match(ui,/data\.modulos\.map/));
test('16 SST se presenta solo por capability',()=>assert.match(service,/modulos:m\.rows\.filter/));
test('17 Documentos conserva configuración contextual existente',()=>assert.ok(read('src/modules/documentos/documentos.checklist.service.ts').includes('requisito_id')));
test('rutas están autenticadas y tenant scoped',()=>{assert.match(routes,/authMiddleware,tenantMiddleware/);assert.match(read('src/routes/index.ts'),/company-settings/)});
test('auditoría central registra general módulos y nómina',()=>{assert.equal((service.match(/registerAuditEntry/g)??[]).length>=3,true)});
