import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
const root = process.cwd();
const saas = readFileSync(join(root, 'src/modules/saas/saas.middleware.ts'), 'utf8');
const ui = readFileSync(join(root, 'FrontendNuevo/src/pages/admin/ConfiguracionGeneral/tabs/NominaProcesosTab.tsx'), 'utf8');
const css = readFileSync(join(root, 'FrontendNuevo/src/pages/nomina/NominaPages.css'), 'utf8');
const routes = readFileSync(join(root, 'src/modules/nomina/nomina.routes.ts'), 'utf8');

test('CompanyContext resolver reconoce rutas históricas :id', () => assert.match(saas, /const genericId = req\.params\.id/));
test('CompanyContext resuelve periodo por id', () => assert.match(saas, /FROM nomina_periodos np/));
test('CompanyContext resuelve empleado por id', () => assert.match(saas, /FROM nomina_empleados ne/));
test('CompanyContext resuelve liquidación por id', () => assert.match(saas, /FROM nomina_liquidaciones nl/));
test('empresa no autorizada sigue bloqueada', () => assert.match(saas, /assertEmpresaModuleEnabled\(empresaId,code,req\.tenant\)/));
test('UX no solicita Usuario ID', () => assert.doesNotMatch(ui, /Usuario ID/));
test('UX no solicita IDs de scope', () => assert.doesNotMatch(ui, /IDs de scope/));
test('UX permite buscar usuarios', () => assert.match(ui, /Buscar usuario/));
test('UX muestra procesos como checkboxes', () => assert.match(ui, /type="checkbox"/));
test('UX muestra municipios humanos', () => assert.match(ui, /nombre_municipio/));
test('UX muestra áreas humanas', () => assert.match(ui, /a\.nombre/));
test('OPS no requiere scope', () => assert.match(ui, /Responsable del proceso|OPS/));
test('NINGUNO tiene advertencia no destructiva', () => assert.match(ui, /sin responsabilidad|Sin asignación/i));
test('responsabilidades existentes se cargan', () => assert.match(ui, /procesos\/responsabilidades/));
test('responsabilidades se persisten', () => assert.match(ui, /apiClient\.put/));
test('áreas se crean sin código manual', () => assert.match(ui, /slugCode/));
test('normalización elimina tildes', () => assert.match(ui, /normalize\('NFD'\)/));
test('código permanece estable al editar', () => assert.match(ui, /nombre: areaName/));
test('áreas se desactivan/reactivan', () => assert.match(ui, /activo: !a\.activo/));
test('áreas inactivas no se asignan', () => assert.match(ui, /areas\.filter\(\(a\) => a\.activo\)/));
test('estado vacío áreas', () => assert.match(ui, /No hay áreas de asistencia configuradas/));
test('estado vacío responsables', () => assert.match(ui, /No hay responsables configurados/));
test('drawer de responsable', () => assert.match(ui, /nomina-drawer/));
test('modal de área', () => assert.match(ui, /nomina-modal/));
test('empresa activa se muestra', () => assert.match(ui, /empresaActual\.nombre_empresa/));
test('rutas de procesos preservadas', () => { assert.match(routes, /procesos\/acceso/); assert.match(routes, /procesos\/areas/); });
test('layout de responsables evita dispersión horizontal', () => assert.match(css, /nomina-responsable-row/));
test('drawer tiene scroll interno', () => assert.match(css, /overflow:auto/));
test('topbar no se modifica desde UX Nómina', () => assert.doesNotMatch(ui, /Topbar|TopBar/));
