import type { QueryResultRow } from 'pg';
import { dbPool, dbQuery } from '../../config/db';
import type { TenantAccessContext } from '../../middlewares/tenantMiddleware';
import { assertTenantAccessForEmpresaId } from '../../middlewares/tenantMiddleware';
import { AppError } from '../../utils/AppError';
import { registerAuditEntry, type AuditRequestMeta } from '../auditoria/auditoria.helper';
import { getEmpresaCapabilities } from '../saas/saas.service';
export interface GeneralConfigInput {nombre_comercial?:string|null;dv?:string|null;pais:string;zona_horaria:string;moneda:string;locale:string;logo_url?:string|null;encabezado_documentos?:string|null;direccion?:string|null;telefono?:string|null;correo?:string|null;ciudad?:string|null;departamento?:string|null}
export interface ModuleConfigInput {estado:'PENDIENTE'|'INCOMPLETA'|'CONFIGURADA';observaciones?:string|null}
export interface PayrollParameterInput {vigente_desde:string;vigente_hasta?:string|null;salario_minimo?:number|null;auxilio_transporte?:number|null;uvt?:number|null;porcentaje_salud_empleado?:number|null;porcentaje_pension_empleado?:number|null;porcentaje_fondo_solidaridad?:number|null;porcentaje_hora_extra_diurna?:number|null;porcentaje_hora_extra_nocturna?:number|null;porcentaje_recargo_nocturno?:number|null;regla_redondeo?:'NEAREST'|'FLOOR'|'CEIL'|'NONE';observaciones?:string|null}
const assertModuleEnabled=async(e:number,c:string,t?:TenantAccessContext)=>{const caps=await getEmpresaCapabilities(e,t);if(!caps.modulos[c])throw new AppError('Module is not enabled for this company',403,'MODULE_NOT_ENABLED');};
export const getCompanyConfiguration=async(e:number,t?:TenantAccessContext)=>{assertTenantAccessForEmpresaId(t,e);const [g,m,caps]=await Promise.all([dbQuery(`SELECT e.id::text,e.nombre_empresa,e.nit,e.direccion,e.telefono,e.correo,e.ciudad,e.departamento,e.activo,o.id::text organizacion_id,o.nombre organizacion_nombre,c.nombre_comercial,c.dv,COALESCE(c.pais,'Colombia') pais,COALESCE(c.zona_horaria,'America/Bogota') zona_horaria,COALESCE(c.moneda,'COP') moneda,COALESCE(c.locale,'es-CO') locale,c.logo_url,c.encabezado_documentos,c.updated_at FROM empresas e JOIN organizaciones o ON o.id=e.organizacion_id LEFT JOIN empresa_configuracion_general c ON c.empresa_id=e.id WHERE e.id=$1`,[e]),dbQuery(`SELECT m.id::text modulo_id,m.codigo,m.nombre,COALESCE(c.estado,'PENDIENTE') estado,c.observaciones,c.updated_at FROM modulos m LEFT JOIN empresa_modulo_configuracion c ON c.modulo_id=m.id AND c.empresa_id=$1 WHERE m.activo=TRUE ORDER BY m.orden,m.id`,[e]),getEmpresaCapabilities(e,t)]);if(!g.rows[0])throw new AppError('Company not found',404,'EMPRESA_NOT_FOUND');return{general:g.rows[0],modulos:m.rows.filter((r:any)=>caps.modulos[r.codigo]).map((r:any)=>({...r,habilitado:true,configurado:r.estado==='CONFIGURADA'}))};};
export const saveGeneralConfiguration=async(e:number,i:GeneralConfigInput,u:string,t?:TenantAccessContext,meta?:AuditRequestMeta)=>{assertTenantAccessForEmpresaId(t,e);const client=await dbPool.connect();try{await client.query('BEGIN');const before=await getCompanyConfiguration(e,t);await client.query(`UPDATE empresas SET direccion=$2,telefono=$3,correo=$4,ciudad=$5,departamento=$6 WHERE id=$1`,[e,i.direccion??null,i.telefono??null,i.correo??null,i.ciudad??null,i.departamento??null]);await client.query(`INSERT INTO empresa_configuracion_general(empresa_id,nombre_comercial,dv,pais,zona_horaria,moneda,locale,logo_url,encabezado_documentos,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(empresa_id) DO UPDATE SET nombre_comercial=EXCLUDED.nombre_comercial,dv=EXCLUDED.dv,pais=EXCLUDED.pais,zona_horaria=EXCLUDED.zona_horaria,moneda=EXCLUDED.moneda,locale=EXCLUDED.locale,logo_url=EXCLUDED.logo_url,encabezado_documentos=EXCLUDED.encabezado_documentos,updated_by=EXCLUDED.updated_by,updated_at=NOW()`,[e,i.nombre_comercial??null,i.dv??null,i.pais,i.zona_horaria,i.moneda,i.locale,i.logo_url??null,i.encabezado_documentos??null,u]);const after={...before.general,...i};await registerAuditEntry({accion:'UPDATE',tabla:'empresa_configuracion_general',registro_id:String(e),descripcion:'Configuración general empresarial actualizada',before:before.general,after,usuario_id:u,client,...meta});await client.query('COMMIT');return await getCompanyConfiguration(e,t);}catch(x){await client.query('ROLLBACK');throw x;}finally{client.release();}};
export const saveModuleConfiguration=async(e:number,c:string,i:ModuleConfigInput,u:string,t?:TenantAccessContext,meta?:AuditRequestMeta)=>{assertTenantAccessForEmpresaId(t,e);await assertModuleEnabled(e,c,t);const mod=await dbQuery<{id:string}&QueryResultRow>('SELECT id::text FROM modulos WHERE codigo=$1 AND activo=TRUE',[c]);const moduleRow=mod.rows[0];if(!moduleRow)throw new AppError('Module is inactive or missing',409,'MODULE_INACTIVE');const r=await dbQuery(`INSERT INTO empresa_modulo_configuracion(empresa_id,modulo_id,estado,observaciones,updated_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(empresa_id,modulo_id) DO UPDATE SET estado=EXCLUDED.estado,observaciones=EXCLUDED.observaciones,updated_by=EXCLUDED.updated_by,updated_at=NOW() RETURNING *`,[e,moduleRow.id,i.estado,i.observaciones??null,u]);const saved=r.rows[0];if(!saved)throw new AppError('Module configuration was not saved',500,'CONFIGURATION_SAVE_FAILED');await registerAuditEntry({accion:'UPSERT',tabla:'empresa_modulo_configuracion',registro_id:String(saved.id),descripcion:`Configuración ${c} actualizada`,after:saved,usuario_id:u,...meta});return saved;};
export const listPayrollParameters=async(e:number,f:string|undefined,t?:TenantAccessContext)=>{assertTenantAccessForEmpresaId(t,e);await assertModuleEnabled(e,'NOMINA',t);const p:any[]=[e];let q='';if(f){p.push(f);q='AND vigente_desde<=$2::date AND (vigente_hasta IS NULL OR vigente_hasta>=$2::date)';}return(await dbQuery(`SELECT * FROM nomina_parametros_economicos WHERE empresa_id=$1 ${q} ORDER BY vigente_desde DESC,id DESC`,p)).rows;};
export const createPayrollParameter=async(e:number,i:PayrollParameterInput,u:string,t?:TenantAccessContext,meta?:AuditRequestMeta)=>{assertTenantAccessForEmpresaId(t,e);await assertModuleEnabled(e,'NOMINA',t);const k=['vigente_desde','vigente_hasta','salario_minimo','auxilio_transporte','uvt','porcentaje_salud_empleado','porcentaje_pension_empleado','porcentaje_fondo_solidaridad','porcentaje_hora_extra_diurna','porcentaje_hora_extra_nocturna','porcentaje_recargo_nocturno','regla_redondeo','observaciones'] as const;const v:any[]=k.map(x=>i[x]??null);v[11]=i.regla_redondeo??'NEAREST';const r=await dbQuery(`INSERT INTO nomina_parametros_economicos(empresa_id,${k.join(',')},created_by) VALUES($1,${k.map((_,n)=>`$${n+2}`).join(',')},$15) RETURNING *`,[e,...v,u]);const saved=r.rows[0];if(!saved)throw new AppError('Payroll parameter was not saved',500,'CONFIGURATION_SAVE_FAILED');await registerAuditEntry({accion:'CREATE',tabla:'nomina_parametros_economicos',registro_id:String(saved.id),descripcion:'Parámetro económico de nómina creado',after:saved,usuario_id:u,...meta});return saved;};
