import type { Request, Response } from 'express';
import { createNominaArea, listNominaAreas, listNominaAssignableUsers, listNominaResponsibilities, replaceNominaResponsibility, updateNominaArea } from './nomina.procesos';
import { successResponse } from '../../utils/apiResponse';

export async function listNominaAreasHandler(req: Request, res: Response) { return successResponse(res, { data: await listNominaAreas(String(req.query.empresa_id ?? ''), req.tenant) }); }
export async function listNominaResponsibilitiesHandler(req: Request, res: Response) { if (!req.query.usuario_id || !req.query.empresa_id) return res.status(400).json({ success: false, message: 'usuario_id y empresa_id son requeridos' }); return successResponse(res, { data: await listNominaResponsibilities(String(req.query.usuario_id), String(req.query.empresa_id), req.tenant) }); }
export async function listNominaAssignableUsersHandler(req: Request, res: Response) { if (!req.query.empresa_id) return res.status(400).json({ success: false, message: 'empresa_id es requerido' }); return successResponse(res, { data: await listNominaAssignableUsers(String(req.query.empresa_id), req.tenant) }); }
export async function replaceNominaResponsibilityHandler(req: Request, res: Response) { const body = req.body ?? {}; if (!body.usuario_id || !body.empresa_id || !body.proceso) return res.status(400).json({ success: false, message: 'usuario_id, empresa_id y proceso son requeridos' }); return successResponse(res, { data: await replaceNominaResponsibility({ usuarioId: body.usuario_id, empresaId: body.empresa_id, proceso: body.proceso, municipioIds: body.municipio_ids, areaIds: body.area_ids }, req.tenant) }); }
export async function createNominaAreaHandler(req: Request, res: Response) { const body = req.body ?? {}; if (!body.empresa_id || !body.codigo || !body.nombre) return res.status(400).json({ success: false, message: 'empresa_id, codigo y nombre son requeridos' }); return successResponse(res, { data: await createNominaArea({ empresaId: body.empresa_id, codigo: body.codigo, nombre: body.nombre, orden: body.orden }, req.tenant) }); }
export async function updateNominaAreaHandler(req: Request, res: Response) { return successResponse(res, { data: await updateNominaArea(String(req.params.area_id), req.body ?? {}, req.tenant) }); }
