import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { operacionApi, type InstitutionResult } from '../../services/operacionApi';
import { getTenantContext } from '../../services/tenantApi';
import { useCompanyContext } from '../../context/CompanyContext';
import { WorkspaceHeading } from '../workspace/StructuralPage';
import './OperacionPages.css';

const empty: InstitutionResult = { items: [], total: 0, page: 1, page_size: 50, total_pages: 0, summary: { instituciones: 0, sedes: 0, combinaciones: 0, matriculados: 0, cupos: 0 }, filter_options: { focalizaciones: [], municipios: [], instituciones: [], sedes: [], modalidades: [], rectores: [], gestores: [], estados: [] }, contrato_id: 0 };
const fmt = (n: number | null) => n == null ? '—' : n.toLocaleString('es-CO');

export default function OperacionInstitucionesFinalPage() {
  const { empresaId } = useCompanyContext(); const [params, setParams] = useSearchParams();
  const [result, setResult] = useState<InstitutionResult>(empty); const [contractId, setContractId] = useState<number | null>(null); const [contracts, setContracts] = useState<Array<{ id: number; numero_contrato: string | null }>>([]); const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle'); const [message, setMessage] = useState(''); const [retry, setRetry] = useState(0);
  const [search, setSearch] = useState(params.get('q') ?? ''); const [focalizacion, setFocalizacion] = useState(params.get('focalizacion_id') ?? ''); const [municipio, setMunicipio] = useState(params.get('municipio_id') ?? ''); const [institution, setInstitution] = useState(params.get('institucion_id') ?? ''); const [site, setSite] = useState(params.get('sede_id') ?? ''); const [modality, setModality] = useState(params.get('modalidad_id') ?? ''); const [rector, setRector] = useState(params.get('rector') ?? ''); const [manager, setManager] = useState(params.get('gestor_id') ?? ''); const [state, setState] = useState(params.get('estado') ?? ''); const [page, setPage] = useState(Number(params.get('page') ?? 1) || 1); const pageSize = Number(params.get('page_size') ?? 50) || 50; void [setSearch, setMunicipio, setInstitution, setSite, setModality, setRector, setManager, setState];
  useEffect(() => { let live = true; void getTenantContext().then((context) => { if (!live) return; const available = context.contratos.filter((contract) => contract.empresa_id === empresaId); setContracts(available); setContractId(context.contrato_default_id && available.some((contract) => contract.id === context.contrato_default_id) ? context.contrato_default_id : available[0]?.id ?? null); }).catch(() => live && (setStatus('error'), setMessage('No fue posible resolver el contrato activo.'))); return () => { live = false; }; }, [empresaId]);
  useEffect(() => { const next = new URLSearchParams(params); next.delete('periodo_id'); Object.entries({ q: search, focalizacion_id: focalizacion, municipio_id: municipio, institucion_id: institution, sede_id: site, modalidad_id: modality, rector, gestor_id: manager, estado: state, page: String(page), page_size: String(pageSize) }).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); setParams(next, { replace: true }); }, [search, focalizacion, municipio, institution, site, modality, rector, manager, state, page, pageSize, setParams]);
  useEffect(() => { if (!contractId) return; let live = true; const timer = window.setTimeout(() => { setStatus('loading'); setMessage(''); setResult(empty); void operacionApi.institutions({ q: search || undefined, focalizacion_id: focalizacion || undefined, municipio_id: municipio || undefined, institucion_id: institution || undefined, sede_id: site || undefined, modalidad_id: modality || undefined, rector: rector || undefined, gestor_id: manager || undefined, estado: state || undefined, contrato_id: contractId, page, page_size: pageSize }).then((response) => { if (live) { setResult(response.data); setStatus('success'); } }).catch((error) => { if (live) { setResult(empty); setStatus('error'); setMessage(error instanceof Error ? error.message : 'No fue posible cargar las instituciones.'); } }); }, 250); return () => { live = false; window.clearTimeout(timer); }; }, [contractId, search, focalizacion, municipio, institution, site, modality, rector, manager, state, page, pageSize, retry]);
  const reset = () => setPage(1);
  return <section className="workspace-page operacion-page instituciones-page"><WorkspaceHeading title="Instituciones" description="Consulta operativa por contrato y focalización mensual." /><div className="instituciones-context"><span>Contrato activo:</span><strong>{contracts[0]?.numero_contrato ?? (contractId ? `Contrato ${contractId}` : 'Resolviendo...')}</strong></div><div className="instituciones-filters"><label>Focalización<select value={focalizacion || 'all'} onChange={(event) => { setFocalizacion(event.target.value === 'all' ? '' : event.target.value); reset(); }}><option value="all">Todas las focalizaciones</option>{result.filter_options.focalizaciones.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label></div>{status === 'loading' && <p className="operacion-message" role="status">Cargando resumen...</p>}{status === 'error' && <div className="operacion-message" role="alert"><span>{message}</span><button type="button" onClick={() => setRetry((value) => value + 1)}>Reintentar</button></div>}{status === 'success' && <div className="instituciones-summary"><strong>{result.summary.instituciones} instituciones</strong><span>·</span><strong>{result.summary.sedes} sedes</strong><span>·</span><strong>{fmt(result.summary.matriculados)} matriculados</strong><span>·</span><strong>{fmt(result.summary.cupos)} cupos</strong></div>}<div className="operacion-table-wrap instituciones-table-wrap"><table><thead><tr><th>Municipio</th><th>Institución</th><th>Sede</th><th>Modalidad</th><th>Estado</th></tr></thead><tbody>{result.items.map((row) => <tr key={`${row.id}-${row.focalizacion.id}`}><td>{row.municipio ?? '—'}</td><td>{row.institucion ?? 'Sin institución'}</td><td>{row.sede ?? 'Sin sede'}</td><td>{row.modalidad ?? 'Sin modalidad'}</td><td>{row.estado}</td></tr>)}{status === 'success' && !result.items.length && <tr><td colSpan={5}>No hay resultados para los filtros actuales.</td></tr>}</tbody></table></div><div className="instituciones-pagination"><span>{result.total ? (result.page - 1) * result.page_size + 1 : 0} - {Math.min(result.page * result.page_size, result.total)} de {result.total}</span><button type="button" disabled={page <= 1 || status === 'loading'} onClick={() => setPage((value) => Math.max(1, value - 1))}>Anterior</button><button type="button" disabled={page >= result.total_pages || status === 'loading'} onClick={() => setPage((value) => value + 1)}>Siguiente</button></div></section>;
}
