import type { PoolClient, QueryResultRow } from 'pg';
import { dbPool } from '../../config/db';
import type { AgendaListQuery } from './agenda.schemas';
import type { AgendaEstado, AgendaScope } from './agenda.types';
type Executor = Pick<PoolClient,'query'>;
const db = (e?:Executor):Executor => e ?? dbPool;

export class AgendaRepository {
  async list(input: AgendaListQuery, scope: AgendaScope) {
    const p:unknown[]=[scope.empresaId]; const w=['t.empresa_id=$1::bigint','t.archivada=FALSE'];
    if(!scope.canManage&&!scope.canAudit){p.push(scope.userId);w.push(`(t.creador_id=$${p.length} OR t.responsable_id=$${p.length} OR EXISTS (SELECT 1 FROM agenda_tarea_participantes tp WHERE tp.tarea_id=t.id AND tp.usuario_id=$${p.length}))`);}
    const add=(sql:string,v:unknown)=>{p.push(v);w.push(sql.replace('$X',`$${p.length}`));};
    if(input.responsable_id) add('t.responsable_id=$X::bigint',input.responsable_id); if(input.creador_id)add('t.creador_id=$X::bigint',input.creador_id);
    if(input.estado)add('t.estado=$X',input.estado);if(input.prioridad)add('t.prioridad=$X',input.prioridad);if(input.tipo)add('t.tipo=$X',input.tipo);if(input.desde)add('t.fecha_prevista>=$X::date',input.desde);if(input.hasta)add('t.fecha_prevista<=$X::date',input.hasta);
    if(input.vencidas)w.push(`t.fecha_limite<CURRENT_DATE AND t.estado IN ('PENDIENTE','EN_PROCESO','REPROGRAMADA')`);if(input.municipio_id)add('t.municipio_id=$X::bigint',input.municipio_id);if(input.institucion_id)add('t.institucion_id=$X::bigint',input.institucion_id);if(input.sede_id)add('t.sede_id=$X::bigint',input.sede_id);if(input.modulo_relacionado)add('t.modulo_relacionado=$X',input.modulo_relacionado);if(input.q){p.push(`%${input.q}%`);w.push(`(t.titulo ILIKE $${p.length} OR COALESCE(t.descripcion,'') ILIKE $${p.length})`);}
    const count=await db().query<{total:number}>(`SELECT COUNT(*)::int total FROM agenda_tareas t WHERE ${w.join(' AND ')}`,p); const offset=(input.page-1)*input.limit;
    const data=await db().query(`SELECT t.*,u.nombre_completo responsable_nombre,c.nombre_completo creador_nombre FROM agenda_tareas t JOIN usuarios u ON u.id=t.responsable_id JOIN usuarios c ON c.id=t.creador_id WHERE ${w.join(' AND ')} ORDER BY t.fecha_prevista ASC,t.prioridad ASC,t.id ASC LIMIT ${input.limit} OFFSET ${offset}`,p);
    return {items:data.rows,page:input.page,limit:input.limit,total:Number(count.rows[0]?.total??0)};
  }
  async listAssignableUsers(input:{search?:string;limit:number},scope:AgendaScope){const params:unknown[]=[scope.empresaId];const where=[`ue.empresa_id=$1::bigint`,`COALESCE(u.activo,TRUE)=TRUE`,`COALESCE(ue.activo,TRUE)=TRUE`];if(input.search){params.push(`%${input.search}%`);where.push(`u.nombre_completo ILIKE $${params.length}`);}params.push(input.limit);return (await db().query(`SELECT u.id,u.nombre_completo,COALESCE(string_agg(DISTINCT r.nombre_rol,', ' ORDER BY r.nombre_rol) FILTER(WHERE r.nombre_rol IS NOT NULL),'') rol FROM usuarios u JOIN usuario_empresas ue ON ue.usuario_id=u.id LEFT JOIN usuario_roles ur ON ur.usuario_id=u.id AND COALESCE(ur.activo,TRUE)=TRUE LEFT JOIN roles r ON r.id=ur.rol_id AND COALESCE(r.activo,TRUE)=TRUE WHERE ${where.join(' AND ')} GROUP BY u.id,u.nombre_completo ORDER BY lower(u.nombre_completo),u.id LIMIT $${params.length}`,params)).rows;}
  async get(id:number,scope:AgendaScope,e?:Executor){const r=await db(e).query(`SELECT t.*,u.nombre_completo responsable_nombre,c.nombre_completo creador_nombre FROM agenda_tareas t JOIN usuarios u ON u.id=t.responsable_id JOIN usuarios c ON c.id=t.creador_id WHERE t.id=$1 AND t.empresa_id=$2 AND t.archivada=FALSE AND ($3 OR t.creador_id=$4 OR t.responsable_id=$4 OR EXISTS(SELECT 1 FROM agenda_tarea_participantes tp WHERE tp.tarea_id=t.id AND tp.usuario_id=$4))`,[id,scope.empresaId,scope.canManage||scope.canAudit,scope.userId]);return r.rows[0]??null;}
  async detail(id:number,scope:AgendaScope,e?:Executor){const r=await db(e).query(`SELECT t.*,u.nombre_completo responsable_nombre,c.nombre_completo creador_nombre,COALESCE((SELECT jsonb_agg(jsonb_build_object('id',p.usuario_id,'nombre',pu.nombre_completo) ORDER BY p.usuario_id) FROM agenda_tarea_participantes p JOIN usuarios pu ON pu.id=p.usuario_id WHERE p.tarea_id=t.id),'[]'::jsonb) participantes,COALESCE((SELECT jsonb_agg(s ORDER BY s.created_at,s.id) FROM agenda_tarea_seguimientos s WHERE s.tarea_id=t.id),'[]'::jsonb) seguimientos,COALESCE((SELECT jsonb_agg(a ORDER BY a.fecha_asignacion,a.id) FROM agenda_tarea_asignaciones a WHERE a.tarea_id=t.id),'[]'::jsonb) asignaciones,COALESCE((SELECT jsonb_agg(s ORDER BY s.created_at,s.id) FROM agenda_tarea_seguimientos s WHERE s.tarea_id=t.id AND s.tipo IN ('REPROGRAMACION')),'[]'::jsonb) reprogramaciones FROM agenda_tareas t JOIN usuarios u ON u.id=t.responsable_id JOIN usuarios c ON c.id=t.creador_id WHERE t.id=$1 AND t.empresa_id=$2 AND t.archivada=FALSE AND ($3 OR t.creador_id=$4 OR t.responsable_id=$4 OR EXISTS(SELECT 1 FROM agenda_tarea_participantes tp WHERE tp.tarea_id=t.id AND tp.usuario_id=$4))`,[id,scope.empresaId,scope.canManage||scope.canAudit,scope.userId]);return r.rows[0]??null;}
  async insert(input:any,scope:AgendaScope,e:Executor){const r=await e.query(`INSERT INTO agenda_tareas(empresa_id,titulo,descripcion,tipo,prioridad,fecha_prevista,hora_inicio,hora_finalizacion,duracion_estimada_minutos,fecha_limite,responsable_id,creador_id,origen,modulo_relacionado,tipo_entidad_relacionada,entidad_relacionada_id,municipio_id,institucion_id,sede_id,persona_id,vinculacion_id,requiere_seguimiento,fecha_proxima_seguimiento) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23) RETURNING *`,[scope.empresaId,input.titulo,input.descripcion??null,input.tipo,input.prioridad,input.fecha_prevista,input.hora_inicio??null,input.hora_finalizacion??null,input.duracion_estimada_minutos??null,input.fecha_limite??null,input.responsable_id,scope.userId,input.origen,input.modulo_relacionado??null,input.tipo_entidad_relacionada??null,input.entidad_relacionada_id??null,input.municipio_id??null,input.institucion_id??null,input.sede_id??null,input.persona_id??null,input.vinculacion_id??null,input.requiere_seguimiento,input.fecha_proxima_seguimiento??null]);return r.rows[0];}
  async participants(id:number,ids:number[],e:Executor){if(ids.length)await e.query(`INSERT INTO agenda_tarea_participantes(tarea_id,usuario_id) SELECT $1,x FROM UNNEST($2::bigint[]) x ON CONFLICT DO NOTHING`,[id,ids]);}
  async replaceParticipants(id:number,ids:number[],scope:AgendaScope,e:Executor){await e.query(`DELETE FROM agenda_tarea_participantes WHERE tarea_id=$1`,[id]);if(ids.length)await e.query(`INSERT INTO agenda_tarea_participantes(tarea_id,usuario_id) SELECT $1,x FROM UNNEST($2::bigint[]) x ON CONFLICT DO NOTHING`,[id,ids]);return this.detail(id,scope,e);}
  async assignment(input:{empresaId:number;tareaId:number;previous:number|null;next:number;assignedBy:number},e:Executor){await e.query(`INSERT INTO agenda_tarea_asignaciones(empresa_id,tarea_id,responsable_anterior_id,responsable_nuevo_id,asignado_por_id,motivo) VALUES($1,$2,$3,$4,$5,$6)`,[input.empresaId,input.tareaId,input.previous,input.next,input.assignedBy,'Asignación inicial']);}
  async update(id:number,input:any,scope:AgendaScope,e:Executor){const allowed=['titulo','descripcion','tipo','prioridad','fecha_prevista','hora_inicio','hora_finalizacion','duracion_estimada_minutos','fecha_limite','modulo_relacionado','tipo_entidad_relacionada','entidad_relacionada_id','municipio_id','institucion_id','sede_id','persona_id','vinculacion_id','requiere_seguimiento','fecha_proxima_seguimiento'];const fields=Object.keys(input).filter(k=>allowed.includes(k));if(!fields.length)return this.get(id,scope,e);const p=fields.map(k=>input[k]);p.push(id,scope.empresaId);const r=await e.query(`UPDATE agenda_tareas SET ${fields.map((k,i)=>`${k}=$${i+1}`).join(',')},version=version+1,updated_at=now() WHERE id=$${p.length-1} AND empresa_id=$${p.length} AND archivada=FALSE RETURNING *`,p);return r.rows[0];}
  async transition(id:number,state:AgendaEstado,comment:string|undefined,scope:AgendaScope,version:number|undefined,e:Executor){const p=[state,scope.empresaId,id,comment??null,...(version?[version]:[])];const v=version?` AND version=$${p.length}`:'';const r=await e.query(`UPDATE agenda_tareas SET estado=$1,fecha_terminacion=CASE WHEN $1='TERMINADA' THEN ((CURRENT_TIMESTAMP AT TIME ZONE 'America/Bogota')::date) ELSE fecha_terminacion END,motivo_cancelacion=CASE WHEN $1='CANCELADA' THEN $4 ELSE motivo_cancelacion END,version=version+1,updated_at=now() WHERE id=$3 AND empresa_id=$2 AND archivada=FALSE${v} RETURNING *`,p);return r.rows[0];}
  async reassign(id:number,newId:number,scope:AgendaScope,motivo:string|undefined,e:Executor){const old=await this.get(id,{...scope,canManage:true},e);if(!old)return null;await e.query(`UPDATE agenda_tareas SET responsable_id=$1,version=version+1,updated_at=now() WHERE id=$2 AND empresa_id=$3`,[newId,id,scope.empresaId]);await e.query(`INSERT INTO agenda_tarea_asignaciones(empresa_id,tarea_id,responsable_anterior_id,responsable_nuevo_id,asignado_por_id,motivo) VALUES($1,$2,$3,$4,$5,$6)`,[scope.empresaId,id,old.responsable_id,newId,scope.userId,motivo??null]);return this.get(id,{...scope,canManage:true},e);}
  async reschedule(id:number,input:any,scope:AgendaScope,e:Executor){const old=await this.get(id,{...scope,canManage:true},e);if(!old)return null;await e.query(`UPDATE agenda_tareas SET fecha_prevista=$1,fecha_limite=$2,estado='REPROGRAMADA',motivo_reprogramacion=$3,version=version+1,updated_at=now() WHERE id=$4 AND empresa_id=$5`,[input.fecha_prevista,input.fecha_limite??null,input.motivo,id,scope.empresaId]);return {old,current:await this.get(id,{...scope,canManage:true},e)};}
  async followup(id:number,input:any,scope:AgendaScope,e:Executor){const r=await e.query(`INSERT INTO agenda_tarea_seguimientos(empresa_id,tarea_id,usuario_id,tipo,comentario,estado_anterior,estado_nuevo,fecha_anterior,fecha_nueva,evidencia_documento_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[scope.empresaId,id,scope.userId,input.tipo,input.comentario,input.estado_anterior??null,input.estado_nuevo??null,input.fecha_anterior??null,input.fecha_nueva??null,input.evidencia_documento_id??null]);return r.rows[0];}
  async history(id:number,scope:AgendaScope){return (await db().query(`SELECT * FROM agenda_tarea_seguimientos WHERE empresa_id=$1 AND tarea_id=$2 ORDER BY created_at ASC,id ASC`,[scope.empresaId,id])).rows;}
  async listFollowups(input:any,scope:AgendaScope){const p:unknown[]=[scope.empresaId];const w=['s.empresa_id=$1::bigint','t.archivada=FALSE'];if(!scope.canManage&&!scope.canAudit){p.push(scope.userId);w.push(`(t.creador_id=$${p.length} OR t.responsable_id=$${p.length} OR EXISTS(SELECT 1 FROM agenda_tarea_participantes p WHERE p.tarea_id=t.id AND p.usuario_id=$${p.length}))`);}const add=(sql:string,v:unknown)=>{p.push(v);w.push(sql.replace('$X',`$${p.length}`));};if(input.desde)add('s.created_at::date>=$X::date',input.desde);if(input.hasta)add('s.created_at::date<=$X::date',input.hasta);if(input.responsable_id)add('t.responsable_id=$X::bigint',input.responsable_id);if(input.tipo)add('s.tipo=$X',input.tipo);if(input.tipo_tarea)add('t.tipo=$X',input.tipo_tarea);if(input.modulo_relacionado)add('t.modulo_relacionado=$X',input.modulo_relacionado);if(input.q){p.push(`%${input.q}%`);w.push(`(t.titulo ILIKE $${p.length} OR COALESCE(s.comentario,'') ILIKE $${p.length})`);}if(input.filtro==='hoy')w.push(`s.created_at::date=((CURRENT_TIMESTAMP AT TIME ZONE 'America/Bogota')::date)`);if(input.filtro==='vencidos')w.push(`t.fecha_proxima_seguimiento<((CURRENT_TIMESTAMP AT TIME ZONE 'America/Bogota')::date)`);if(input.filtro==='proximos')w.push(`t.fecha_proxima_seguimiento>=((CURRENT_TIMESTAMP AT TIME ZONE 'America/Bogota')::date)`);if(input.filtro==='realizados')w.push(`s.tipo IN ('CIERRE','COMENTARIO')`);const offset=(input.page-1)*input.limit;const count=await db().query<{total:number}>(`SELECT COUNT(*)::int total FROM agenda_tarea_seguimientos s JOIN agenda_tareas t ON t.id=s.tarea_id WHERE ${w.join(' AND ')}`,p);const data=await db().query(`SELECT s.*,t.titulo,t.estado,t.responsable_id,t.modulo_relacionado,t.fecha_proxima_seguimiento,u.nombre_completo responsable_nombre,au.nombre_completo usuario_registro_nombre FROM agenda_tarea_seguimientos s JOIN agenda_tareas t ON t.id=s.tarea_id JOIN usuarios u ON u.id=t.responsable_id JOIN usuarios au ON au.id=s.usuario_id WHERE ${w.join(' AND ')} ORDER BY s.created_at DESC,s.id DESC LIMIT ${input.limit} OFFSET ${offset}`,p);return {items:data.rows,page:input.page,limit:input.limit,total:Number(count.rows[0]?.total??0)};}
  async top(date:string,scope:AgendaScope,e:Executor){return (await e.query(`SELECT tt.*,t.titulo,t.estado,t.prioridad FROM agenda_top_tareas tt JOIN agenda_tareas t ON t.id=tt.tarea_id WHERE tt.empresa_id=$1 AND tt.usuario_id=$2 AND tt.fecha=$3 ORDER BY tt.posicion`,[scope.empresaId,scope.userId,date])).rows;}
  async accessibleTasks(ids:number[],scope:AgendaScope,e:Executor){if(!ids.length)return [];return (await e.query(`SELECT t.id FROM agenda_tareas t WHERE t.id=ANY($1::bigint[]) AND t.empresa_id=$2 AND t.archivada=FALSE AND ($3 OR t.creador_id=$4 OR t.responsable_id=$4 OR EXISTS(SELECT 1 FROM agenda_tarea_participantes p WHERE p.tarea_id=t.id AND p.usuario_id=$4))`,[ids,scope.empresaId,scope.canManage||scope.canAudit,scope.userId])).rows;}
  async replaceTop(date:string,ids:number[],scope:AgendaScope,e:Executor){await e.query(`DELETE FROM agenda_top_tareas WHERE empresa_id=$1 AND usuario_id=$2 AND fecha=$3`,[scope.empresaId,scope.userId,date]);if(ids.length)await e.query(`INSERT INTO agenda_top_tareas(empresa_id,usuario_id,fecha,tarea_id,posicion) SELECT $1,$2,$3,x,ord FROM UNNEST($4::bigint[]) WITH ORDINALITY q(x,ord)`,[scope.empresaId,scope.userId,date,ids]);return this.top(date,scope,e);}
  async summary(scope:AgendaScope){return (await db().query(`SELECT COUNT(*) FILTER(WHERE estado IN('PENDIENTE','EN_PROCESO','REPROGRAMADA'))::int pendientes,COUNT(*) FILTER(WHERE fecha_prevista=((CURRENT_TIMESTAMP AT TIME ZONE 'America/Bogota')::date) AND estado NOT IN('TERMINADA','CANCELADA'))::int para_hoy,COUNT(*) FILTER(WHERE fecha_limite<((CURRENT_TIMESTAMP AT TIME ZONE 'America/Bogota')::date) AND estado IN('PENDIENTE','EN_PROCESO','REPROGRAMADA'))::int vencidas,COUNT(*) FILTER(WHERE estado='TERMINADA')::int terminadas,COUNT(*) FILTER(WHERE fecha_proxima_seguimiento=((CURRENT_TIMESTAMP AT TIME ZONE 'America/Bogota')::date))::int seguimientos_hoy FROM agenda_tareas t WHERE empresa_id=$1 AND archivada=FALSE AND ($2 OR creador_id=$3 OR responsable_id=$3 OR EXISTS(SELECT 1 FROM agenda_tarea_participantes p WHERE p.tarea_id=t.id AND p.usuario_id=$3))`,[scope.empresaId,scope.canManage||scope.canAudit,scope.userId])).rows[0];}
  async closeDay(input:any,scope:AgendaScope,e:Executor){const selected=[...(input.terminadas??[]).map((id:number)=>[id,'TERMINADA']),...(input.pendientes??[]).map((id:number)=>[id,'PENDIENTE']),...(input.reprogramadas??[]).map((id:number)=>[id,'REPROGRAMADA'])];const ids=[...new Set(selected.map(x=>x[0]))];if(ids.length){const valid=await e.query(`SELECT id,estado FROM agenda_tareas WHERE empresa_id=$1 AND id=ANY($2::bigint[]) AND archivada=FALSE`,[scope.empresaId,ids]);if(valid.rowCount!==ids.length)throw new Error('AGENDA_CIERRE_TAREA_EMPRESA_INVALIDA');for(const [id,clasificacion] of selected){const row=valid.rows.find(x=>Number(x.id)===Number(id));if(!row||((clasificacion==='TERMINADA'&&row.estado!=='TERMINADA')||(clasificacion==='REPROGRAMADA'&&row.estado!=='REPROGRAMADA')||(clasificacion==='PENDIENTE'&&!['PENDIENTE','EN_PROCESO'].includes(row.estado))))throw new Error('AGENDA_CIERRE_CLASIFICACION_INVALIDA');}}const r=await e.query(`INSERT INTO agenda_cierres_diarios(empresa_id,usuario_id,fecha,resumen,resumen_dia,terminadas,pendientes,reprogramadas,observaciones) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(empresa_id,usuario_id,fecha) DO UPDATE SET resumen=EXCLUDED.resumen,resumen_dia=EXCLUDED.resumen_dia,terminadas=EXCLUDED.terminadas,pendientes=EXCLUDED.pendientes,reprogramadas=EXCLUDED.reprogramadas,observaciones=EXCLUDED.observaciones,version=agenda_cierres_diarios.version+1,updated_at=now() RETURNING *`,[scope.empresaId,scope.userId,input.fecha,input.resumen_dia??input.resumen??null,input.resumen_dia??input.resumen??null,null,null,null,input.observaciones??null]);const cierre=r.rows[0];await e.query(`DELETE FROM agenda_cierre_tareas WHERE empresa_id=$1 AND cierre_id=$2`,[scope.empresaId,cierre.id]);if(selected.length)await e.query(`INSERT INTO agenda_cierre_tareas(empresa_id,cierre_id,tarea_id,clasificacion) SELECT $1,$2,x::bigint,c FROM UNNEST($3::bigint[],$4::text[]) q(x,c)`,[scope.empresaId,cierre.id,selected.map(x=>x[0]),selected.map(x=>x[1])]);return cierre;}
  async getCloseDay(date:string,scope:AgendaScope){const r=await db().query(`SELECT c.*,COALESCE(jsonb_agg(jsonb_build_object('tarea_id',ct.tarea_id,'clasificacion',ct.clasificacion)) FILTER(WHERE ct.id IS NOT NULL),'[]'::jsonb) tareas FROM agenda_cierres_diarios c LEFT JOIN agenda_cierre_tareas ct ON ct.cierre_id=c.id AND ct.empresa_id=c.empresa_id WHERE c.empresa_id=$1 AND c.usuario_id=$2 AND c.fecha=$3 GROUP BY c.id`,[scope.empresaId,scope.userId,date]);return r.rows[0]??null;}
  async userBelongs(id:number,empresaId:number,e:Executor){return ((await e.query(`SELECT 1 FROM usuario_empresas WHERE usuario_id=$1 AND empresa_id=$2 AND COALESCE(activo,TRUE)`,[id,empresaId])).rowCount ?? 0)>0;}
  async usersBelong(ids:number[],empresaId:number,e:Executor){if(!ids.length)return new Set<number>();const r=await e.query<{id:number}>(`SELECT usuario_id id FROM usuario_empresas WHERE empresa_id=$1 AND usuario_id=ANY($2::bigint[]) AND COALESCE(activo,TRUE)`,[empresaId,ids]);return new Set(r.rows.map(x=>Number(x.id)));}
  async validateReferences(input:any,empresaId:number,e:Executor){
    const r=await e.query<{ok:boolean}>(`SELECT
      ($1::bigint IS NULL OR EXISTS(SELECT 1 FROM municipios WHERE id=$1)) ok_municipio,
      ($2::bigint IS NULL OR EXISTS(SELECT 1 FROM instituciones i JOIN contratos c ON c.id=i.contrato_id WHERE i.id=$2 AND c.empresa_id=$5)) ok_institucion,
      ($3::bigint IS NULL OR EXISTS(SELECT 1 FROM sedes s JOIN instituciones i ON i.id=s.institucion_id JOIN contratos c ON c.id=i.contrato_id WHERE s.id=$3 AND c.empresa_id=$5 AND ($2::bigint IS NULL OR s.institucion_id=$2))) ok_sede,
      ($4::bigint IS NULL OR EXISTS(SELECT 1 FROM vinculaciones v JOIN contratos c ON c.id=v.contrato_id WHERE v.persona_id=$4 AND c.empresa_id=$5 AND ($6::bigint IS NULL OR v.id=$6))) ok_persona,
      ($6::bigint IS NULL OR EXISTS(SELECT 1 FROM vinculaciones v JOIN contratos c ON c.id=v.contrato_id WHERE v.id=$6 AND c.empresa_id=$5 AND ($4::bigint IS NULL OR v.persona_id=$4))) ok_vinculacion`,[input.municipio_id??null,input.institucion_id??null,input.sede_id??null,input.persona_id??null,empresaId,input.vinculacion_id??null]);
    const row:any=r.rows[0]??{}; if(Object.values(row).some(v=>v===false))throw new Error('AGENDA_REFERENCE_COMPANY_INVALID');
  }
}
export const agendaRepository=new AgendaRepository();
