import type { Request, Response } from 'express';
import { asyncHandler } from '../../utils/asyncHandler';
import { successResponse } from '../../utils/apiResponse';
import { AppError } from '../../utils/AppError';
import * as s from './agenda.service';
import * as z from './agenda.schemas';
const actor=(r:Request)=>{if(!r.user?.userId)throw new AppError('Authentication required',401,'UNAUTHORIZED');return r.user.userId;};
const perms=(r:Request)=>r.user?.permissions??[]; const meta=(r:Request)=>({ip:r.ip,user_agent:String(r.headers['user-agent']??'')});
export const listTasksHandler=asyncHandler(async(r:Request,res:Response)=>successResponse(res,{data:await s.listTasks(z.listTasksSchema.parse(r.query),actor(r),r.tenant,perms(r))}));
export const assignableUsersHandler=asyncHandler(async(r:Request,res:Response)=>successResponse(res,{data:await s.listAssignableUsers(z.assignableUsersSchema.parse(r.query),actor(r),r.tenant,perms(r))}));
export const getTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.getTask(z.taskIdSchema.parse(r.params).id,actor(r),r.tenant,perms(r))}));
export const createTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{statusCode:201,data:await s.createTask(z.createTaskSchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const updateTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.updateTask(z.taskIdSchema.parse(r.params).id,z.updateTaskSchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const assignTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.assignTask(z.taskIdSchema.parse(r.params).id,z.assignSchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const participantsHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.replaceParticipants(z.taskIdSchema.parse(r.params).id,z.participantsSchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const startTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.startTask(z.taskIdSchema.parse(r.params).id,z.transitionSchema.parse(r.body).comentario,z.transitionSchema.parse(r.body).version,actor(r),r.tenant,perms(r),meta(r))}));
export const completeTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.completeTask(z.taskIdSchema.parse(r.params).id,z.transitionSchema.parse(r.body).comentario,z.transitionSchema.parse(r.body).version,actor(r),r.tenant,perms(r),meta(r))}));
export const reopenTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.reopenTask(z.taskIdSchema.parse(r.params).id,z.transitionSchema.parse(r.body).comentario,z.transitionSchema.parse(r.body).version,actor(r),r.tenant,perms(r),meta(r))}));
export const rescheduleTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.rescheduleTask(z.taskIdSchema.parse(r.params).id,z.rescheduleSchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const cancelTaskHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.cancelTask(z.taskIdSchema.parse(r.params).id,z.cancelSchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const followupHandler=asyncHandler(async(r,res)=>successResponse(res,{statusCode:201,data:await s.addFollowup(z.taskIdSchema.parse(r.params).id,z.followupSchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const historyHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.history(z.taskIdSchema.parse(r.params).id,actor(r),r.tenant,perms(r))}));
export const followupsHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.listFollowups(z.followupListSchema.parse(r.query),actor(r),r.tenant,perms(r))}));
export const summaryHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.summary(actor(r),r.tenant,perms(r))}));
export const topHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.replaceTop(z.topSchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const closeDayHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.closeDay(z.closeDaySchema.parse(r.body),actor(r),r.tenant,perms(r),meta(r))}));
export const getCloseDayHandler=asyncHandler(async(r,res)=>successResponse(res,{data:await s.getCloseDay(z.closeDaySchema.shape.fecha.parse(String(r.query.fecha)),actor(r),r.tenant,perms(r))}));
