import type { PoolClient } from 'pg';
import { dbPool } from '../../config/db';
import { registerAuditEntry, type AuditRequestMeta } from '../auditoria/auditoria.helper';
import { assertTenantAccessForEmpresaId, type TenantAccessContext } from '../../middlewares/tenantMiddleware';
import { AppError } from '../../utils/AppError';
import { agendaRepository } from './agenda.repository';
import type { AgendaEstado, AgendaScope } from './agenda.types';
import type { AgendaListQuery } from './agenda.schemas';

const transitions: Record<AgendaEstado, AgendaEstado[]> = {
  PENDIENTE:['EN_PROCESO','TERMINADA','REPROGRAMADA','CANCELADA'], EN_PROCESO:['TERMINADA','REPROGRAMADA','CANCELADA'],
  REPROGRAMADA:['PENDIENTE','EN_PROCESO'], TERMINADA:['PENDIENTE'], CANCELADA:['PENDIENTE']
};
const actorId=(id:string|number)=>{const n=Number(id);if(!Number.isInteger(n)||n<1)throw new AppError('Usuario autenticado invalido',401,'UNAUTHORIZED');return n;};
const company=(tenant:TenantAccessContext|undefined):number=>{if(!tenant||tenant.empresaIds.length!==1)throw new AppError('Debe existir una empresa activa para operar Agenda',403,'AGENDA_EMPRESA_REQUERIDA');return tenant.empresaIds[0]!;};
const scope=(actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[]):AgendaScope=>{const empresaId=company(tenant);assertTenantAccessForEmpresaId(tenant,empresaId);return {empresaId,userId:actorId(actor),canManage:permissions.includes('agenda.manage'),canAudit:permissions.includes('agenda.audit')};};
async function validateUsers(ids:number[],empresaId:number,e:PoolClient){const expected=[...new Set(ids)];const found=await agendaRepository.usersBelong(expected,empresaId,e);if(expected.some(id=>!found.has(id)))throw new AppError('Usuario no pertenece a la empresa',403,'AGENDA_USUARIO_EMPRESA_INVALIDA');}
const compatible:Record<string,string[]>={PERSONAL:['PERSONA','VINCULACION'],COBERTURA:['INSTITUCION','SEDE','VINCULACION'],NOMINA:['VINCULACION','CONTRATO','PERIODO'],DOCUMENTOS:['DOCUMENTO'],SST:['CASO_SST','PERSONA'],REMISIONES:['REMISION'],CONTRATOS:['CONTRATO'],ADMINISTRACION:['PERSONA','VINCULACION']};
async function validateInput(input:any,empresaId:number,e:PoolClient){if(input.modulo_relacionado&&input.tipo_entidad_relacionada&&!compatible[input.modulo_relacionado]?.includes(input.tipo_entidad_relacionada))throw new AppError('Referencia incompatible con el modulo',400,'AGENDA_REFERENCIA_INVALIDA');await agendaRepository.validateReferences(input,empresaId,e);}
async function audit(e:PoolClient,action:string,id:number,userId:number,before:any,after:any,meta?:AuditRequestMeta){await registerAuditEntry({client:e,usuario_id:String(userId),accion:action,tabla:'agenda_tareas',registro_id:String(id),descripcion:`Agenda: ${action}`,before,after,...meta});}
export async function listTasks(query:AgendaListQuery,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[]){return agendaRepository.list(query,scope(actor,tenant,permissions));}
export async function listAssignableUsers(query:{search?:string;limit:number},actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[]){if(!permissions.some(p=>['agenda.create','agenda.assign','agenda.update','agenda.manage'].includes(p)))throw new AppError('Sin permiso para consultar usuarios asignables',403,'AGENDA_ASSIGNABLE_USERS_FORBIDDEN');return agendaRepository.listAssignableUsers(query,scope(actor,tenant,permissions));}
export async function getTask(id:number,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[]){const s=scope(actor,tenant,permissions);const row=await agendaRepository.detail(id,s);if(!row)throw new AppError('Tarea no encontrada',404,'AGENDA_TAREA_NOT_FOUND');return row;}
export async function createTask(input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){const s=scope(actor,tenant,permissions);const e=await dbPool.connect();try{await e.query('BEGIN');await validateUsers([s.userId,input.responsable_id,...(input.participantes??[])],s.empresaId,e);await validateInput(input,s.empresaId,e);const row=await agendaRepository.insert(input,s,e);await agendaRepository.assignment({empresaId:s.empresaId,tareaId:row.id,previous:null,next:input.responsable_id,assignedBy:s.userId},e);await agendaRepository.participants(row.id,input.participantes??[],e);await audit(e,'CREATE',row.id,s.userId,null,row,meta);await e.query('COMMIT');return row;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
export async function updateTask(id:number,input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){const s=scope(actor,tenant,permissions);const e=await dbPool.connect();try{await e.query('BEGIN');const before=await agendaRepository.get(id,{...s,canManage:true},e);if(!before)throw new AppError('Tarea no encontrada',404,'AGENDA_TAREA_NOT_FOUND');if(!s.canManage&&before.creador_id!==s.userId&&before.responsable_id!==s.userId)throw new AppError('Sin alcance sobre la tarea',403,'AGENDA_FORBIDDEN');if(input.estado)throw new AppError('Use el endpoint de transición',409,'AGENDA_TRANSICION_REQUERIDA');if(input.responsable_id)throw new AppError('Use el endpoint de asignacion',409,'AGENDA_ASIGNACION_REQUERIDA');await validateInput(input,s.empresaId,e);const row=await agendaRepository.update(id,input,s,e);await audit(e,'UPDATE',id,s.userId,before,row,meta);await e.query('COMMIT');return row;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
async function transition(id:number,state:AgendaEstado,comment:string|undefined,version:number|undefined,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){const s=scope(actor,tenant,permissions);const e=await dbPool.connect();try{await e.query('BEGIN');const before=await agendaRepository.get(id,{...s,canManage:true},e);if(!before)throw new AppError('Tarea no encontrada',404,'AGENDA_TAREA_NOT_FOUND');if(!s.canManage&&before.responsable_id!==s.userId&&before.creador_id!==s.userId)throw new AppError('Sin alcance sobre la tarea',403,'AGENDA_FORBIDDEN');if(!transitions[before.estado as AgendaEstado]?.includes(state))throw new AppError('Transicion de estado no permitida',409,'AGENDA_TRANSICION_INVALIDA');if(state==='TERMINADA'&&before.estado==='TERMINADA')throw new AppError('Tarea ya terminada',409,'AGENDA_VERSION_CONFLICT');const row=await agendaRepository.transition(id,state,comment,s,version,e);if(!row)throw new AppError('La tarea fue modificada por otro usuario',409,'AGENDA_VERSION_CONFLICT');await agendaRepository.followup(id,{tipo:state==='TERMINADA'?'CIERRE':'CAMBIO_ESTADO',comentario:comment??`Estado: ${state}`,estado_anterior:before.estado,estado_nuevo:state},s,e);await audit(e,`STATUS_${state}`,id,s.userId,before,row,meta);await e.query('COMMIT');return row;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
export const startTask=(...a:any[])=>transition(a[0],'EN_PROCESO',a[1],a[2],a[3],a[4],a[5],a[6]);
export const completeTask=(...a:any[])=>transition(a[0],'TERMINADA',a[1],a[2],a[3],a[4],a[5],a[6]);
export const reopenTask=(...a:any[])=>transition(a[0],'PENDIENTE',a[1],a[2],a[3],a[4],a[5],a[6]);
export async function assignTask(id:number,input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){if(!permissions.includes('agenda.assign')&&!permissions.includes('agenda.manage'))throw new AppError('Sin permiso para asignar tareas',403,'FORBIDDEN');const s=scope(actor,tenant,permissions),e=await dbPool.connect();try{await e.query('BEGIN');await validateUsers([input.responsable_id],s.empresaId,e);const before=await agendaRepository.get(id,{...s,canManage:true},e);const row=await agendaRepository.reassign(id,input.responsable_id,s,input.motivo,e);if(!row||!before)throw new AppError('Tarea no encontrada',404,'AGENDA_TAREA_NOT_FOUND');await agendaRepository.followup(id,{tipo:'REASIGNACION',comentario:input.motivo??'Responsable actualizado'},s,e);await audit(e,'ASSIGN',id,s.userId,before,row,meta);await e.query('COMMIT');return row;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
export async function replaceParticipants(id:number,input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){if(!permissions.includes('agenda.update')&&!permissions.includes('agenda.manage'))throw new AppError('Sin permiso para actualizar participantes',403,'FORBIDDEN');const s=scope(actor,tenant,permissions),e=await dbPool.connect();try{await e.query('BEGIN');const before=await agendaRepository.get(id,{...s,canManage:true},e);if(!before)throw new AppError('Tarea no encontrada',404,'AGENDA_TAREA_NOT_FOUND');if(input.participantes.includes(Number(before.responsable_id)))throw new AppError('El responsable no puede duplicarse como participante',400,'AGENDA_PARTICIPANTE_RESPONSABLE_DUPLICADO');if(new Set(input.participantes).size!==input.participantes.length)throw new AppError('No se permiten participantes duplicados',400,'AGENDA_PARTICIPANTES_DUPLICADOS');await validateUsers(input.participantes,s.empresaId,e);const row=await agendaRepository.replaceParticipants(id,input.participantes,s,e);await agendaRepository.followup(id,{tipo:'COMENTARIO',comentario:'Participantes actualizados'},s,e);await audit(e,'PARTICIPANTS_UPDATE',id,s.userId,before,row,meta);await e.query('COMMIT');return row;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
export async function rescheduleTask(id:number,input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){const s=scope(actor,tenant,permissions),e=await dbPool.connect();try{await e.query('BEGIN');const result=await agendaRepository.reschedule(id,input,s,e);if(!result)throw new AppError('Tarea no encontrada',404,'AGENDA_TAREA_NOT_FOUND');await agendaRepository.followup(id,{tipo:'REPROGRAMACION',comentario:input.motivo,fecha_anterior:result.old.fecha_prevista,fecha_nueva:input.fecha_prevista},s,e);await audit(e,'RESCHEDULE',id,s.userId,result.old,result.current,meta);await e.query('COMMIT');return result.current;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
export async function cancelTask(id:number,input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){return transition(id,'CANCELADA',input.motivo,input.version,actor,tenant,permissions,meta);}
export async function addFollowup(id:number,input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){const s=scope(actor,tenant,permissions);if(input.evidencia_documento_id)throw new AppError('La referencia física de evidencias documentales se habilitará con la integración documental',409,'AGENDA_EVIDENCIA_FUERA_DE_FASE');const e=await dbPool.connect();try{await e.query('BEGIN');const row=await agendaRepository.get(id,s,e);if(!row)throw new AppError('Tarea no encontrada',404,'AGENDA_TAREA_NOT_FOUND');const f=await agendaRepository.followup(id,input,s,e);await audit(e,'FOLLOWUP',id,s.userId,null,f,meta);await e.query('COMMIT');return f;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
export async function history(id:number,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[]){const s=scope(actor,tenant,permissions);if(!(await agendaRepository.get(id,s)))throw new AppError('Tarea no encontrada',404,'AGENDA_TAREA_NOT_FOUND');return agendaRepository.history(id,s);}
export async function listFollowups(input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[]){return agendaRepository.listFollowups(input,scope(actor,tenant,permissions));}
export async function summary(actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[]){const s=scope(actor,tenant,permissions);const [data,top]=await Promise.all([agendaRepository.summary(s),agendaRepository.top(new Date().toLocaleDateString('en-CA',{timeZone:'America/Bogota'}),s,dbPool)]);return {...data,top_3:top};}
export async function replaceTop(input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){const s=scope(actor,tenant,permissions),e=await dbPool.connect();try{await e.query('BEGIN');if(input.tarea_ids.length>3)throw new AppError('El Top 3 admite máximo tres tareas',400,'AGENDA_TOP_MAXIMO');if(new Set(input.tarea_ids).size!==input.tarea_ids.length)throw new AppError('No se permiten tareas duplicadas en Top 3',400,'AGENDA_TOP_DUPLICADO');const accessible=await agendaRepository.accessibleTasks(input.tarea_ids,s,e);if(accessible.length!==input.tarea_ids.length)throw new AppError('Tarea fuera del alcance',403,'AGENDA_FORBIDDEN');const rows=await agendaRepository.replaceTop(input.fecha,input.tarea_ids,s,e);await registerAuditEntry({client:e,usuario_id:String(s.userId),accion:'TOP_UPDATE',tabla:'agenda_top_tareas',registro_id:`${s.userId}:${input.fecha}`,descripcion:'Agenda: Top 3 actualizado',after:input.tarea_ids,...meta});await e.query('COMMIT');return rows;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
export async function closeDay(input:any,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[],meta?:AuditRequestMeta){const s=scope(actor,tenant,permissions),e=await dbPool.connect();try{await e.query('BEGIN');const row=await agendaRepository.closeDay(input,s,e);await audit(e,'CLOSE_DAY',row.id,s.userId,null,row,meta);await e.query('COMMIT');return row;}catch(err){await e.query('ROLLBACK');throw err;}finally{e.release();}}
export async function getCloseDay(date:string,actor:string|number,tenant:TenantAccessContext|undefined,permissions:string[]){return agendaRepository.getCloseDay(date,scope(actor,tenant,permissions));}
