import { Router } from 'express';
import { authMiddleware } from '../../middlewares/authMiddleware';
import { tenantMiddleware } from '../../middlewares/tenantMiddleware';
import { requireModule } from '../saas/saas.middleware';
import { requireAnyPermissions } from '../../middlewares/roleMiddleware';
import * as c from './agenda.controller';
import { agendaTenant } from './agenda.tenant';
const router=Router(); router.use(authMiddleware,tenantMiddleware,agendaTenant,requireModule('AGENDA_OPERATIVA'));
router.get('/resumen',requireAnyPermissions('agenda.read','agenda.manage'),c.summaryHandler);
router.get('/usuarios-asignables',requireAnyPermissions('agenda.create','agenda.assign','agenda.update','agenda.manage','agenda.read'),c.assignableUsersHandler);
router.get('/seguimientos',requireAnyPermissions('agenda.read','agenda.manage'),c.followupsHandler);
router.get('/tareas',requireAnyPermissions('agenda.read','agenda.manage'),c.listTasksHandler); router.get('/tareas/:id',requireAnyPermissions('agenda.read','agenda.manage'),c.getTaskHandler);
router.post('/tareas',requireAnyPermissions('agenda.create','agenda.manage'),c.createTaskHandler); router.patch('/tareas/:id',requireAnyPermissions('agenda.update','agenda.manage'),c.updateTaskHandler);
router.post('/tareas/:id/asignar',requireAnyPermissions('agenda.assign','agenda.manage'),c.assignTaskHandler); router.post('/tareas/:id/iniciar',requireAnyPermissions('agenda.update','agenda.manage'),c.startTaskHandler);
router.put('/tareas/:id/participantes',requireAnyPermissions('agenda.update','agenda.manage'),c.participantsHandler);
router.post('/tareas/:id/terminar',requireAnyPermissions('agenda.complete','agenda.manage'),c.completeTaskHandler); router.post('/tareas/:id/reprogramar',requireAnyPermissions('agenda.update','agenda.manage'),c.rescheduleTaskHandler);
router.post('/tareas/:id/cancelar',requireAnyPermissions('agenda.cancel','agenda.manage'),c.cancelTaskHandler); router.post('/tareas/:id/reabrir',requireAnyPermissions('agenda.reopen','agenda.manage'),c.reopenTaskHandler);
router.post('/tareas/:id/seguimientos',requireAnyPermissions('agenda.update','agenda.manage'),c.followupHandler); router.get('/tareas/:id/historial',requireAnyPermissions('agenda.read','agenda.manage'),c.historyHandler);
router.get('/top',requireAnyPermissions('agenda.read','agenda.update','agenda.manage'),c.getTopHandler);
router.post('/top',requireAnyPermissions('agenda.update','agenda.manage'),c.topHandler); router.post('/cierre-diario',requireAnyPermissions('agenda.update','agenda.manage'),c.closeDayHandler);
router.get('/cierre-diario',requireAnyPermissions('agenda.update','agenda.manage'),c.getCloseDayHandler);
export { router as agendaRoutes };
