import { useEffect, useState } from 'react';
import { Plus, X } from 'lucide-react';
import { getAjustesManuales, createAjusteManual, updateAjusteManual, annulAjusteManual, getNominaPeriodos, getAllNominaPeriodoEmpleados } from '../../services/nominaApi';
import type { AjusteManualApi, NominaEmpleadoApi, NominaPeriodoApi } from '../../types/nomina.types';
import CoberturaFlowNav from './CoberturaFlowNav';
import './NominaPages.css';

const money = (value: number) => `$${Number(value).toLocaleString('es-CO')}`;
export default function AjustesManualesPage() {
  const [periods, setPeriods] = useState<NominaPeriodoApi[]>([]); const [periodId, setPeriodId] = useState('');
  const [items, setItems] = useState<AjusteManualApi[]>([]); const [employees, setEmployees] = useState<NominaEmpleadoApi[]>([]); const [error, setError] = useState('');
  const [form, setForm] = useState({ empleado: '', tipo: 'ADICION' as 'ADICION'|'DEDUCCION', concepto: 'OTRO', valor: '', observacion: '' });
  const load = async (id: string) => { if (!id) return; try { const [a, e] = await Promise.all([getAjustesManuales(id), getAllNominaPeriodoEmpleados(id)]); setItems(a); setEmployees(e.items); } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible cargar ajustes'); } };
  useEffect(() => { getNominaPeriodos({ page: 1, limit: 100 }).then((data) => { setPeriods(data.items); setPeriodId(data.items[0]?.id ?? ''); }).catch(() => setError('No fue posible cargar periodos')); }, []);
  useEffect(() => { void load(periodId); }, [periodId]);
  const save = async () => { const value = Number(form.valor); if (!form.empleado || !form.concepto.trim() || !Number.isFinite(value) || value <= 0) { setError('Empleado, concepto y valor positivo son obligatorios.'); return; } try { await createAjusteManual(periodId, { nomina_empleado_id: form.empleado, tipo: form.tipo, concepto: form.concepto, valor: value, observacion: form.observacion || null }); setForm({ ...form, valor: '', observacion: '' }); await load(periodId); } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible crear el ajuste'); } };
  const edit = async (item: AjusteManualApi) => { const raw = window.prompt('Nuevo valor', String(item.valor)); if (!raw) return; const value = Number(raw); if (!Number.isFinite(value) || value <= 0) return; await updateAjusteManual(item.id, { valor: value }); await load(periodId); };
  const annul = async (item: AjusteManualApi) => { const reason = window.prompt('Motivo de anulación'); if (!reason) return; await annulAjusteManual(item.id, reason); await load(periodId); };
  return <div className="np-page"><CoberturaFlowNav periodId={periodId} /><header className="np-header"><div><h1>Ajustes manuales</h1><p>Adiciones y deducciones económicas independientes de novedades y turnos.</p></div></header>{error && <div className="np-inline-state error">{error}<button onClick={() => setError('')}><X size={14}/></button></div>}<div className="np-toolbar"><select className="np-select" value={periodId} onChange={e => setPeriodId(e.target.value)}>{periods.map(p => <option key={p.id} value={p.id}>{p.nombre_periodo}</option>)}</select></div><section className="np-table-card" style={{padding:16}}><h2>Nuevo ajuste</h2><div className="np-toolbar"><select className="np-select" value={form.empleado} onChange={e => setForm({...form, empleado:e.target.value})}><option value="">Empleado</option>{employees.map(e => <option key={e.id} value={e.id}>{e.persona.nombre_completo} · {e.persona.numero_documento ?? 'sin documento'}</option>)}</select><select className="np-select" value={form.tipo} onChange={e => setForm({...form, tipo:e.target.value as 'ADICION'|'DEDUCCION'})}><option value="ADICION">ADICIÓN</option><option value="DEDUCCION">DEDUCCIÓN</option></select><input className="np-input" placeholder="Concepto" value={form.concepto} onChange={e => setForm({...form, concepto:e.target.value})}/><input className="np-input" type="number" min="0.01" placeholder="Valor" value={form.valor} onChange={e => setForm({...form, valor:e.target.value})}/><input className="np-input" placeholder="Observación" value={form.observacion} onChange={e => setForm({...form, observacion:e.target.value})}/><button className="np-btn primary" onClick={() => void save()}><Plus size={15}/> Nuevo ajuste</button></div></section><div className="np-table-card"><div className="np-table-scroll"><table className="np-table"><thead><tr><th>Empleado</th><th>Documento</th><th>Tipo</th><th>Concepto</th><th>Valor</th><th>Observación</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.empleado}</td><td>{item.numero_documento ?? '—'}</td><td>{item.tipo}</td><td>{item.concepto}</td><td>{money(item.valor)}</td><td>{item.observacion ?? '—'}</td><td>{item.activo ? 'Activo' : `Anulado${item.motivo_anulacion ? `: ${item.motivo_anulacion}` : ''}`}</td><td>{item.activo && <><button className="np-btn" onClick={() => void edit(item)}>Editar</button><button className="np-btn" onClick={() => void annul(item)}>Anular</button></>}</td></tr>)}</tbody></table></div></div></div>;
}
