import { useEffect, useMemo, useState } from 'react';
import { Eye, FileText } from 'lucide-react';
import { useCompanyContext } from '../../context/CompanyContext';
import { getAllNominaTurnos, getCoberturaExternos, getNominaPeriodos, generarCoberturaCuenta, descargarCoberturaCuenta } from '../../services/nominaApi';
import type { CoberturaExternoResumenApi, NominaPeriodoApi, NominaTurno } from '../../types/nomina.types';
import CoberturaFlowNav from './CoberturaFlowNav';
import './NominaPages.css';

const money = (n: number) => `$${Number(n).toLocaleString('es-CO')}`;
export default function CuentasCobroPage() {
  const { empresaId } = useCompanyContext(); const [periods, setPeriods] = useState<NominaPeriodoApi[]>([]); const [periodId, setPeriodId] = useState(''); const [rows, setRows] = useState<CoberturaExternoResumenApi[]>([]); const [turns, setTurns] = useState<NominaTurno[]>([]); const [selected, setSelected] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const period = periods.find(p => p.id === periodId);
  const load = async (id: string) => { if (!id) return; const [external, movements] = await Promise.all([getCoberturaExternos(id, empresaId ? String(empresaId) : undefined), getAllNominaTurnos({ periodo_id: id, activo: true })]); setRows(external); setTurns(movements.items.filter(m => m.tipo_movimiento === 'TURNO_EXTERNO')); };
  useEffect(() => { getNominaPeriodos({ page: 1, limit: 100 }).then(d => { setPeriods(d.items); setPeriodId(d.items[0]?.id ?? ''); }); }, []);
  useEffect(() => { void load(periodId); }, [periodId]);
  const detail = useMemo(() => { if (!selected) return []; return turns.filter(t => t.externo_id === selected); }, [selected, turns]);
  const generate = async (row: CoberturaExternoResumenApi) => { if (!period || !empresaId) return; setBusy(row.id); try { await generarCoberturaCuenta(String(empresaId), String(period.contrato_id), period.id, row.id); await load(period.id); } finally { setBusy(null); } };
  return <div className="np-page"><CoberturaFlowNav periodId={periodId} /><header className="np-header"><div><h1>Cuentas de cobro</h1><p>Consolidado de cuentas externas por persona y periodo.</p></div></header><div className="np-toolbar"><select className="np-select" value={periodId} onChange={e => setPeriodId(e.target.value)}>{periods.map(p => <option key={p.id} value={p.id}>{p.nombre_periodo}</option>)}</select></div><div className="np-table-card"><div className="np-table-scroll"><table className="np-table"><thead><tr><th>Externo</th><th>Cédula</th><th>Periodo</th><th>Turnos</th><th>Total días</th><th>Valor total</th><th>Documentos</th><th>Estado</th><th>Número cuenta</th><th>Fecha generación</th><th>Acciones</th></tr></thead><tbody>{rows.map(row => { const own = turns.filter(t => t.externo_id === row.id); const days = own.reduce((s,t) => s + (t.cantidad ?? 1), 0); return <tr key={row.id}><td>{row.nombre_completo}</td><td>{row.numero_documento}</td><td>{period?.nombre_periodo ?? '—'}</td><td>{own.length || row.turnos}</td><td>{days}</td><td>{money(row.valor_total)}</td><td>{row.cedula && row.banco_doc ? 'Completos' : 'Pendientes'}</td><td>{row.cuenta_estado}</td><td>{row.cuenta_id ?? '—'}</td><td>{row.cuenta_estado === 'PENDIENTE' ? '—' : 'Generada'}</td><td><button className="np-btn" onClick={() => setSelected(row.id)}><Eye size={14}/> Gestionar</button>{row.cuenta_estado === 'PENDIENTE' ? <button className="np-btn primary" disabled={busy !== null} onClick={() => void generate(row)}>{busy === row.id ? 'Generando...' : 'Generar'}</button> : row.cuenta_id ? <button className="np-btn" onClick={() => void descargarCoberturaCuenta(row.cuenta_id!).then(r => window.open(r.url, '_blank'))}><FileText size={14}/> Ver PDF</button> : null}</td></tr>; })}</tbody></table></div></div>{selected && <section className="np-table-card" style={{padding:16}}><h2>Detalle de cuenta · {rows.find(r => r.id === selected)?.nombre_completo}</h2><p>Datos del externo · {rows.find(r => r.id === selected)?.numero_documento} · Estado {rows.find(r => r.id === selected)?.cuenta_estado}</p><h3>Turnos incluidos</h3><div className="np-table-scroll"><table className="np-table"><thead><tr><th>Persona cubierta</th><th>Fecha</th><th>Días</th><th>Tarifa diaria</th><th>Subtotal</th></tr></thead><tbody>{detail.map(t => <tr key={t.id}><td>{t.persona_reemplazada?.nombre_completo ?? 'No disponible'}</td><td>{t.fecha ?? '—'}</td><td>{t.cantidad ?? 1}</td><td>{t.valor_unitario ? money(t.valor_unitario) : 'SIN TARIFA'}</td><td>{t.valor_unitario ? money(t.valor_total) : 'TARIFA PENDIENTE'}</td></tr>)}</tbody></table></div></section>}</div>;
}
