import { useEffect,useMemo,useRef,useState } from "react";
import { AlertTriangle,ChevronRight,Plus,Search,X } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";
import { apiClient } from "../../services/apiClient";
import { createNominaNovedad,getAllNominaMovimientos,getAllNominaNovedades,getAllNominaPeriodoEmpleados,getNominaPeriodos } from "../../services/nominaApi";
import type { NominaEmpleadoApi,NominaMovimientoApi,NominaNovedadApi,NominaPeriodoApi } from "../../types/nomina.types";
import type { ApiResponse } from "../../types/api.types";
import { buildTramos,dateKey,isOutsideEmployment,movimientosOnDate,novedadCode,novedadesOnDate,novedadState,type PlanillaCambio,type PlanillaContexto } from "./planillaOperativa.domain";
import "./PlanillaOperativaPage.css";

const ROW_H=58,VIEW_H=560,OVERSCAN=6,CELL_W=48,DOC_W=122,NAME_W=244;
const CODES=["PR1","PR2","PR3","PR4","PNR","S","L50"];
type Filter="TODOS"|"CON_NOVEDADES"|"SIN_NOVEDADES"|"PENDIENTES"|"INCONSISTENCIAS"|"CON_TA"|"CON_CAMBIOS";
interface Selected{employee:NominaEmpleadoApi;date:string;context:PlanillaContexto;novedades:NominaNovedadApi[];movimientos:NominaMovimientoApi[];change:boolean}
const contextText=(c:PlanillaContexto)=>[c.municipio,c.institucion,c.sede,c.modalidad].filter(Boolean).join(" · ")||"Contexto operativo sin etiqueta";
const groupBy=<T,>(items:T[],key:(item:T)=>string)=>{const map=new Map<string,T[]>();for(const item of items){const k=key(item);map.set(k,[...(map.get(k)??[]),item]);}return map;};
const weekday=(date:string)=>new Intl.DateTimeFormat("es-CO",{weekday:"narrow",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`)).toUpperCase();
export default function PlanillaOperativaPage(){
 const {user}=useAuth();const [periods,setPeriods]=useState<NominaPeriodoApi[]>([]),[periodId,setPeriodId]=useState("2");const [employees,setEmployees]=useState<NominaEmpleadoApi[]>([]),[novedades,setNovedades]=useState<NominaNovedadApi[]>([]),[moves,setMoves]=useState<NominaMovimientoApi[]>([]),[changes,setChanges]=useState<PlanillaCambio[]>([]);const [loading,setLoading]=useState(true),[error,setError]=useState("");
 const [search,setSearch]=useState(""),[filter,setFilter]=useState<Filter>("TODOS"),[municipio,setMunicipio]=useState(""),[modalidad,setModalidad]=useState("");const [scrollTop,setScrollTop]=useState(0),[selected,setSelected]=useState<Selected|null>(null),[editor,setEditor]=useState<{employee:NominaEmpleadoApi;date:string;code:string}|null>(null),[saving,setSaving]=useState(false);const viewport=useRef<HTMLDivElement>(null);
 const period=periods.find(p=>String(p.id)===periodId);const start=period?.fecha_inicio??"2026-08-01",end=period?.fecha_fin??"2026-08-31";const days=useMemo(()=>Array.from({length:Number(end.slice(8))},(_,i)=>dateKey(Number(start.slice(0,4)),Number(start.slice(5,7)),i+1)),[start,end]);
 const canCreate=user?.permissions.includes("nomina.novedades.create")===true;const editable=period?.estado==="ABIERTO"&&canCreate;
 useEffect(()=>{void getNominaPeriodos({page:1,limit:100}).then(r=>setPeriods(r.items)).catch(e=>setError(String(e)));},[]);
 const load=async()=>{setLoading(true);setError("");try{const [e,n,m,c]=await Promise.all([getAllNominaPeriodoEmpleados(periodId),getAllNominaNovedades({periodo_id:periodId,activo:true}),getAllNominaMovimientos({periodo_id:periodId,activo:true}),apiClient.get<ApiResponse<PlanillaCambio[]>>("/nomina/cambios-operativos",{params:{periodo_id:periodId,activo:true}})]);if(!Array.isArray(e.items)||!Array.isArray(n.items)||!Array.isArray(m.items)||!Array.isArray(c?.data))throw new Error("La respuesta de planilla tiene una estructura inválida");setEmployees(e.items);setNovedades(n.items);setMoves(m.items);setChanges(c.data);}catch(e){setEmployees([]);setNovedades([]);setMoves([]);setChanges([]);setError(e instanceof Error?e.message:"No fue posible cargar la planilla");}finally{setLoading(false);}};
 // load is intentionally recreated with the selected period.
 // oxlint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void load();},[periodId]);
 const novByEmployee=useMemo(()=>groupBy(novedades,n=>n.nomina_empleado_id),[novedades]);const moveByEmployee=useMemo(()=>groupBy(moves,m=>m.nomina_empleado_id),[moves]);const changeByLink=useMemo(()=>groupBy(changes,c=>c.vinculacion_id),[changes]);
 const filtered=useMemo(()=>employees.filter(e=>{const ns=novByEmployee.get(String(e.id))??[],ms=moveByEmployee.get(String(e.id))??[],cs=changeByLink.get(String(e.vinculacion_id))??[];const hayTa=ms.some(m=>m.familia_movimiento==="ADICION_DEVENGO"),inconsistent=ms.some(m=>m.posible_duplicado||m.alertas_validacion.some(a=>a.severidad==="ERROR"||a.severidad==="WARNING"));const q=search.trim().toLowerCase();if(q&&!`${e.persona.nombre_completo} ${e.persona.numero_documento??""}`.toLowerCase().includes(q))return false;if(municipio&&(e.sede?.municipio??e.municipio??"")!==municipio)return false;if(modalidad&&(e.modalidad??e.categoria_salarial?.modalidad??"")!==modalidad)return false;return filter==="TODOS"||(filter==="CON_NOVEDADES"&&ns.length>0)||(filter==="SIN_NOVEDADES"&&ns.length===0)||(filter==="PENDIENTES"&&ns.some(n=>novedadState(n)==="REQUIERE_REVISION"))||(filter==="INCONSISTENCIAS"&&inconsistent)||(filter==="CON_TA"&&hayTa)||(filter==="CON_CAMBIOS"&&cs.length>0);}),[employees,search,filter,municipio,modalidad,novByEmployee,moveByEmployee,changeByLink]);
 const startIndex=Math.max(0,Math.floor(scrollTop/ROW_H)-OVERSCAN),visibleCount=Math.ceil(VIEW_H/ROW_H)+OVERSCAN*2,visible=filtered.slice(startIndex,startIndex+visibleCount);const summary=useMemo(()=>({nov:employees.filter(e=>(novByEmployee.get(String(e.id))?.length??0)>0).length,pending:employees.filter(e=>(novByEmployee.get(String(e.id))??[]).some(n=>novedadState(n)==="REQUIERE_REVISION")).length,ta:employees.filter(e=>(moveByEmployee.get(String(e.id))??[]).some(m=>m.familia_movimiento==="ADICION_DEVENGO")).length,changes:new Set(changes.map(c=>c.vinculacion_id)).size,incons:moves.filter(m=>m.posible_duplicado||m.alertas_validacion.length>0).length}),[employees,novByEmployee,moveByEmployee,changes,moves]);
 const jump=(from:number)=>{viewport.current?.querySelector<HTMLElement>(`[data-day="${from}"]`)?.scrollIntoView({behavior:"smooth",inline:"start",block:"nearest"});};
 const inspect=(e:NominaEmpleadoApi,date:string)=>{const tramos=buildTramos(e,start,end,changeByLink.get(String(e.vinculacion_id))??[]);const tramo=tramos.find(t=>t.inicio<=date&&t.fin>=date);const ns=novedadesOnDate(novByEmployee.get(String(e.id))??[],date),ms=movimientosOnDate(moveByEmployee.get(String(e.id))??[],date);setSelected({employee:e,date,context:tramo?.contexto??{},novedades:ns,movimientos:ms,change:tramo?.inicio===date&&tramo.cambioId!==null});};
 const keyCell=(ev:React.KeyboardEvent,e:NominaEmpleadoApi,date:string,row:number,col:number)=>{if(ev.key.startsWith("Arrow")){ev.preventDefault();const nr=row+(ev.key==="ArrowDown"?1:ev.key==="ArrowUp"?-1:0),nc=col+(ev.key==="ArrowRight"?1:ev.key==="ArrowLeft"?-1:0);document.querySelector<HTMLElement>(`[data-cell="${nr}-${nc}"]`)?.focus();return;}if(ev.key==="Enter"){ev.preventDefault();inspect(e,date);if(editable)setEditor({employee:e,date,code:""});}else if(ev.key==="Escape")setEditor(null);else if(editable&&/^[a-zA-Z0-9]$/.test(ev.key)){setEditor({employee:e,date,code:ev.key.toUpperCase()});}};
 const saveCode=async()=>{if(!editor||!CODES.includes(editor.code.toUpperCase()))return;setSaving(true);try{await createNominaNovedad({periodo_id:periodId,nomina_empleado_id:String(editor.employee.id),vinculacion_id:String(editor.employee.vinculacion_id),tipo_novedad_codigo:editor.code.toUpperCase(),fecha_inicio:editor.date,fecha_fin:editor.date,observacion:"Captura rápida planilla 1-31"});setEditor(null);await load();}finally{setSaving(false);}};
 const municipios=Array.from(new Set(employees.map(e=>e.sede?.municipio??e.municipio).filter(Boolean))) as string[],modalidades=Array.from(new Set(employees.map(e=>e.modalidad??e.categoria_salarial?.modalidad).filter(Boolean))) as string[];
 return <section className="op-sheet-page"><header className="op-sheet-title"><div><span>NÓMINA OPERATIVA</span><h1>{period?.nombre_periodo??"AGOSTO 2026"}</h1></div><strong className={`op-period-state ${period?.estado==="ABIERTO"?"open":"locked"}`}>{period?.estado??"CARGANDO"} · NOVEDADES EN PROCESO</strong></header>
 <div className="op-summary"><strong>{employees.length} trabajadores</strong><span>{summary.nov} con novedades</span><span>{summary.pending} pendientes</span><span>{summary.ta} con TA</span><span>{summary.changes} con cambios</span><span>{summary.incons} inconsistencias</span></div>
 <div className="op-toolbar"><label><Search size={15}/><input aria-label="Buscar trabajador" placeholder="Nombre o documento" value={search} onChange={e=>setSearch(e.target.value)}/></label><select value={periodId} onChange={e=>setPeriodId(e.target.value)}>{periods.map(p=><option key={String(p.id)} value={String(p.id)}>{p.nombre_periodo}</option>)}</select><select value={filter} onChange={e=>setFilter(e.target.value as Filter)}><option value="TODOS">Todos</option><option value="CON_NOVEDADES">Con novedades</option><option value="SIN_NOVEDADES">Sin novedades</option><option value="PENDIENTES">Pendientes</option><option value="INCONSISTENCIAS">Inconsistencias</option><option value="CON_TA">Con TA</option><option value="CON_CAMBIOS">Con cambios</option></select><select value={municipio} onChange={e=>setMunicipio(e.target.value)}><option value="">Municipios</option>{municipios.map(x=><option key={x}>{x}</option>)}</select><select value={modalidad} onChange={e=>setModalidad(e.target.value)}><option value="">Modalidades</option>{modalidades.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="op-jumps">{[[1,7],[8,14],[15,21],[22,28],[29,31]].map(([a,b])=><button key={a} onClick={()=>jump(a!)}>{a}–{b}</button>)}</div>
 {error&&<div className="op-error"><AlertTriangle size={16}/>{error}</div>}{loading?<div className="op-loading">Cargando 771 filas y eventos…</div>:<div ref={viewport} className="op-viewport" onScroll={e=>setScrollTop(e.currentTarget.scrollTop)} style={{height:VIEW_H}}>
  <div className="op-grid op-head" style={{gridTemplateColumns:`${DOC_W}px ${NAME_W}px repeat(${days.length},${CELL_W}px)`}}><div className="op-doc">DOCUMENTO</div><div className="op-name">TRABAJADOR</div>{days.map((d,i)=><div key={d} data-day={i+1} className="op-day-head"><b>{String(i+1).padStart(2,"0")}</b><small>{weekday(d)}</small></div>)}</div>
  <div className="op-virtual-space" style={{height:filtered.length*ROW_H,width:DOC_W+NAME_W+days.length*CELL_W}}>{visible.map((e,local)=>{const idx=startIndex+local,tramos=buildTramos(e,start,end,changeByLink.get(String(e.vinculacion_id))??[]),rowN=novByEmployee.get(String(e.id))??[],rowM=moveByEmployee.get(String(e.id))??[];return <div key={String(e.id)} className={`op-grid op-row ${selected?.employee.id===e.id?"selected":""}`} style={{gridTemplateColumns:`${DOC_W}px ${NAME_W}px repeat(${days.length},${CELL_W}px)`,top:idx*ROW_H,height:ROW_H}}><div className="op-doc">{e.persona.numero_documento??"—"}</div><div className="op-name"><strong>{e.persona.nombre_completo}</strong><small>{contextText(tramos[0]?.contexto??{})}</small></div>{days.map((date,col)=>{const outside=isOutsideEmployment(e,date),ns=novedadesOnDate(rowN,date),ms=movimientosOnDate(rowM,date),tas=ms.filter(m=>m.familia_movimiento==="ADICION_DEVENGO"),tramo=tramos.find(t=>t.inicio<=date&&t.fin>=date),change=tramo?.inicio===date&&tramo.cambioId!==null,multi=ns.length+tas.length+(change?1:0)>1;return <button type="button" key={date} data-cell={`${idx}-${col}`} className={`op-cell ${outside?"outside":""} ${change?"change":""} ${selected?.employee.id===e.id&&selected.date===date?"active":""}`} title={outside?"FUERA DE VINCULACIÓN":`${date}\n${contextText(tramo?.contexto??{})}`} onClick={()=>inspect(e,date)} onDoubleClick={()=>editable&&setEditor({employee:e,date,code:""})} onKeyDown={ev=>keyCell(ev,e,date,idx,col)}><span>{ns.slice(0,1).map(n=><b key={n.id} data-state={novedadState(n)}>{novedadCode(n)}</b>)}</span>{tas.length>0&&<em>TA{tas.length>1?` +${tas.length-1}`:""}</em>}{change&&<i>C</i>}{multi&&<sup>•</sup>}</button>})}</div>})}</div>
 </div>}
 {selected&&<aside className="op-inspector"><button className="op-close" onClick={()=>setSelected(null)}><X/></button><div><strong>{selected.employee.persona.nombre_completo}</strong><span>CC ••••{selected.employee.persona.numero_documento?.slice(-4)??"----"} · {selected.date}</span><p>{contextText(selected.context)}</p></div><div className="op-inspector-events">{selected.novedades.map(n=><span key={n.id}>{novedadCode(n)} · {novedadState(n)}</span>)}{selected.movimientos.filter(m=>m.familia_movimiento==="ADICION_DEVENGO").map(m=><span key={m.id}>TA · {contextText(m.contexto_operativo??{})} · {m.estado}</span>)}{selected.change&&<span>CAMBIO OPERATIVO</span>}{selected.novedades.length===0&&selected.movimientos.length===0&&!selected.change&&<span>Sin eventos</span>}</div><div className="op-actions"><button disabled={!editable} onClick={()=>setEditor({employee:selected.employee,date:selected.date,code:""})}><Plus size={14}/> Novedad</button><Link to="/nomina">Rango / editar / soporte</Link><Link to="/nomina/turnos">Crear TA <ChevronRight size={14}/></Link><Link to="/nomina/cambios-operativos">Ver cambios</Link></div></aside>}
 {editor&&<div className="op-quick"><strong>{editor.employee.persona.nombre_completo} · {editor.date}</strong><input autoFocus list="op-codes" placeholder="PR1, PNR, S…" value={editor.code} onChange={e=>setEditor({...editor,code:e.target.value.toUpperCase()})} onKeyDown={e=>{if(e.key==="Enter")void saveCode();if(e.key==="Escape")setEditor(null);}}/><datalist id="op-codes">{CODES.map(c=><option key={c}>{c}</option>)}</datalist><button disabled={saving||!CODES.includes(editor.code)} onClick={()=>void saveCode()}>Registrar</button><button onClick={()=>setEditor(null)}>Cancelar</button><small>Para rangos, soportes y edición avanzada use “Novedades”.</small></div>}
 </section>;
}
