[CmdletBinding()]
param([Parameter(Mandatory=$true)][long]$ActorUserId)
$ErrorActionPreference='Stop'
$projectRef='scuvsocqibbubqnesvuf'
. (Join-Path $PSScriptRoot 'psql-connection.ps1')
$databaseUrl=[Environment]::GetEnvironmentVariable('PRODUCTION_MIGRATION_DATABASE_URL','Process')
if([string]::IsNullOrWhiteSpace($databaseUrl)){throw 'PRODUCTION_MIGRATION_DATABASE_URL es obligatorio.'}
if([Environment]::GetEnvironmentVariable('SUPABASE_PROJECT_REF','Process') -ne $projectRef){throw 'SUPABASE_PROJECT_REF no coincide con el proyecto aprobado.'}
foreach($name in @('INTEGRACION_OUTBOX_ENABLED','INTEGRACION_SYNC_ENABLED','INTEGRACION_RECALC_ENABLED')){ $value=[Environment]::GetEnvironmentVariable($name,'Process'); if($value -and $value.ToLowerInvariant() -eq 'true'){throw "$name debe permanecer false o ausente."} }
if($ActorUserId -le 0){throw 'ActorUserId explícito es obligatorio.'}
$connection=$null;$psqlPath=$null;$previousEnv=@{};$pgEnvNames=@('PGHOST','PGPORT','PGDATABASE','PGUSER','PGPASSWORD','PGSSLMODE','PGCONNECT_TIMEOUT')
function Get-Psql17Path { foreach($candidate in @('C:\Program Files\PostgreSQL\17\bin\psql.exe',((Get-Command psql -ErrorAction SilentlyContinue).Source))){if([string]::IsNullOrWhiteSpace($candidate)-or !(Test-Path -LiteralPath $candidate)){continue};$v=(& $candidate --version|Out-String).Trim();if($v -match 'PostgreSQL\)\s+17\.'){return $candidate}};throw 'Se exige psql PostgreSQL 17.x.' }
function Set-Env { foreach($n in $pgEnvNames){$previousEnv[$n]=[Environment]::GetEnvironmentVariable($n,'Process')};[Environment]::SetEnvironmentVariable('PGHOST',$connection.Host,'Process');[Environment]::SetEnvironmentVariable('PGPORT',[string]$connection.Port,'Process');[Environment]::SetEnvironmentVariable('PGDATABASE',$connection.Database,'Process');[Environment]::SetEnvironmentVariable('PGUSER',$connection.User,'Process');[Environment]::SetEnvironmentVariable('PGPASSWORD',$connection.Password,'Process');[Environment]::SetEnvironmentVariable('PGSSLMODE','require','Process');[Environment]::SetEnvironmentVariable('PGCONNECT_TIMEOUT',[string]$connection.ConnectTimeout,'Process') }
function Restore-Env { foreach($n in $pgEnvNames){[Environment]::SetEnvironmentVariable($n,$previousEnv[$n],'Process')} }
try { $connection=Get-PsqlConnectionParameters -ConnectionString $databaseUrl -ExpectedProjectRef $projectRef;$psqlPath=Get-Psql17Path;Set-Env;Write-Host ("Correccion trazabilidad: actor_id={0}, host={1}, port={2}, database={3}, cliente={4}" -f $ActorUserId,$connection.Host,$connection.Port,(Get-SanitizedPsqlValue $connection.Database),(& $psqlPath --version).Trim());$confirmation=Read-Host "Escriba exactamente CORREGIR TRAZABILIDAD PERIODOS 4 6 ACTOR $ActorUserId SOLO anulado_por $projectRef";if($confirmation -cne "CORREGIR TRAZABILIDAD PERIODOS 4 6 ACTOR $ActorUserId SOLO anulado_por $projectRef"){throw 'Confirmacion invalida; no se ejecutaron escrituras.'};$args=@('-h',$connection.Host,'-p',[string]$connection.Port,'-U',$connection.User,'-d',$connection.Database,'--no-psqlrc','--quiet','--set=ON_ERROR_STOP=1','--set','actor_user_id='+[string]$ActorUserId,'--file',(Join-Path $PSScriptRoot 'fix-periodos-4-6-anulado-por.sql'));& $psqlPath @args;if($LASTEXITCODE-ne 0){throw 'Correccion falló; transaccion revertida.'};Write-Host 'Correccion completada o idempotente; solo anulado_por fue considerado.' } finally { if($previousEnv.Count-gt 0){Restore-Env} }
