import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiClient } from '../../../../services/apiClient';
import { configuracionApi } from '../../../../services/configuracionApi';
import { useCompanyContext } from '../../../../context/CompanyContext';

type Parameter = { id:number|string; vigente_desde:string; vigente_hasta?:string|null; salario_minimo?:number|string|null; auxilio_transporte?:number|string|null };
type Category = { id:number|string; contrato_id:number|string; numero_contrato?:string|null; codigo_categoria:string; nombre_categoria:string; modalidad?:string|null; salario_base:number|string; auxilio_transporte:number|string; otros_recargos?:number|string|null; vigente_desde:string; vigente_hasta?:string|null; activo:boolean };
const money=(v:unknown)=>v==null||v===''?'—':new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(v));
const today=()=>new Date().toISOString().slice(0,10);

export function PayrollParametersTab(){
 const {empresaActual}=useCompanyContext(); const [rows,setRows]=useState<Parameter[]>([]); const [open,setOpen]=useState(false); const [form,setForm]=useState<Record<string,unknown>>({vigente_desde:today(),regla_redondeo:'NEAREST'}); const [error,setError]=useState('');
 const load=useCallback(async()=>{if(empresaActual)setRows((await apiClient.get<{data:Parameter[]}>(`/company-settings/${empresaActual.id}/payroll-parameters`)).data)},[empresaActual]); useEffect(()=>{void load()},[load]);
 const current=rows[0]; const f=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v})); const save=async()=>{if(!empresaActual)return;try{await apiClient.post(`/company-settings/${empresaActual.id}/payroll-parameters`,{...form,...Object.fromEntries(Object.entries(form).filter(([,v])=>v!==''&&v!==undefined))});setOpen(false);setError('');await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar') }};
 if(!empresaActual)return <div className="adm-empty">Seleccione una empresa autorizada.</div>;
 return <section className="nomina-economic"><div className="adm-card"><div className="nomina-section-head"><div><h3>Parámetros base</h3><p>Referencias generales de empresa; no sobrescriben valores específicos de categoría.</p></div><button className="adm-btn primary" onClick={()=>setOpen(true)}>+ Nueva vigencia</button></div>{current?<><div className="nomina-economic-grid"><div><h4>Referencia general</h4><p>Salario mínimo/base <strong>{money(current.salario_minimo)}</strong></p><p>Auxilio de transporte de referencia <strong>{money(current.auxilio_transporte)}</strong></p><p>Vigencia <strong>{current.vigente_desde} – {current.vigente_hasta??'abierta'}</strong></p></div><div><p className="nomina-config-note">El salario y auxilio de una categoría prevalecen para el cálculo operativo. Esta referencia no sincroniza ni modifica categorías.</p></div></div><h4>Historial</h4><table className="adm-history"><thead><tr><th>Desde</th><th>Hasta</th><th>Salario base</th><th>Auxilio referencia</th><th>Estado</th></tr></thead><tbody>{rows.map(r=><tr key={String(r.id)}><td>{r.vigente_desde}</td><td>{r.vigente_hasta??'Abierta'}</td><td>{money(r.salario_minimo)}</td><td>{money(r.auxilio_transporte)}</td><td><span className="adm-status active">Vigente</span></td></tr>)}</tbody></table></>:<p>No hay parámetros configurados.</p>}</div>{open&&<div className="nomina-drawer-backdrop"><aside className="nomina-drawer"><button className="nomina-close" onClick={()=>setOpen(false)}>×</button><h3>Nueva vigencia base</h3>{[['vigente_desde','Vigencia desde'],['vigente_hasta','Vigencia hasta'],['salario_minimo','Salario mínimo/base'],['auxilio_transporte','Auxilio de transporte de referencia']].map(([k,l])=><label key={k}>{l}<input type={k.includes('vigente')?'date':'number'} value={String(form[k]??'')} onChange={e=>f(k,e.target.value===''?'':k.includes('vigente')?e.target.value:Number(e.target.value))}/></label>)}{error&&<p role="alert">{error}</p>}<div className="nomina-drawer-actions"><button className="adm-btn ghost" onClick={()=>setOpen(false)}>Cancelar</button><button className="adm-btn primary" onClick={()=>void save()}>Guardar vigencia</button></div></aside></div>}</section>;
}

export function SalaryCategoriesTab(){
 const {empresaActual}=useCompanyContext(); const [rows,setRows]=useState<Category[]>([]); const [contracts,setContracts]=useState<Array<{id:number|string;numero_contrato?:string}>>([]); const [q,setQ]=useState(''); const [active,setActive]=useState('TODOS'); const [open,setOpen]=useState(false); const [form,setForm]=useState<Record<string,unknown>>({vigente_desde:today(),salario_base:0,auxilio_transporte:0,activo:true});
 const load=useCallback(async()=>{if(!empresaActual)return;const [cats,cs]=await Promise.all([apiClient.get<{data:Category[]}>(`/company-settings/${empresaActual.id}/salary-categories`),configuracionApi.listarContratos({empresa_id:empresaActual.id,limit:500})]);setRows(cats.data);setContracts((cs.items??[]) as Array<{id:number|string;numero_contrato?:string}>);},[empresaActual]); useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>rows.filter(r=>(active==='TODOS'||(active==='ACTIVOS'?r.activo:!r.activo))&&`${r.codigo_categoria} ${r.nombre_categoria}`.toLowerCase().includes(q.toLowerCase())),[rows,q,active]); const f=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v})); const save=async()=>{if(!empresaActual)return;await apiClient.post(`/company-settings/${empresaActual.id}/salary-categories`,{...form,contrato_id:Number(form.contrato_id),salario_base:Number(form.salario_base),auxilio_transporte:Number(form.auxilio_transporte)});setOpen(false);await load()};
 if(!empresaActual)return <div className="adm-empty">Seleccione una empresa autorizada.</div>;
 return <section className="nomina-economic"><div className="adm-card"><div className="nomina-section-head"><div><h3>Categorías salariales</h3><p>Valores específicos por contrato y categoría; conservan histórico.</p></div><button className="adm-btn primary" onClick={()=>setOpen(true)}>+ Nueva vigencia</button></div><div className="nomina-assignment-filters"><input placeholder="Buscar código o nombre" value={q} onChange={e=>setQ(e.target.value)}/><select value={active} onChange={e=>setActive(e.target.value)}><option value="TODOS">Todas</option><option value="ACTIVOS">Vigentes</option><option value="INACTIVOS">Inactivas</option></select></div><table className="adm-history"><thead><tr><th>Código / nombre</th><th>Contrato</th><th>Salario base</th><th>Auxilio transporte</th><th>Recargos adicionales</th><th>Vigencia</th><th>Estado</th></tr></thead><tbody>{visible.map(r=><tr key={String(r.id)}><td><strong>{r.codigo_categoria}</strong><br/><small>{r.nombre_categoria}</small></td><td>{r.numero_contrato??r.contrato_id}</td><td>{money(r.salario_base)}</td><td>{money(r.auxilio_transporte)}</td><td>{money(r.otros_recargos)}</td><td>{r.vigente_desde} – {r.vigente_hasta??'abierta'}</td><td><span className={`adm-status ${r.activo?'active':'inactive'}`}>{r.activo?'Activa':'Inactiva'}</span></td></tr>)}</tbody></table></div>{open&&<div className="nomina-drawer-backdrop"><aside className="nomina-drawer"><button className="nomina-close" onClick={()=>setOpen(false)}>×</button><h3>Nueva categoría/vigencia</h3><label>Contrato<select value={String(form.contrato_id??'')} onChange={e=>f('contrato_id',e.target.value)}><option value="">Seleccione</option>{contracts.map(c=><option key={String(c.id)} value={String(c.id)}>{c.numero_contrato??c.id}</option>)}</select></label>{[['codigo_categoria','Código'],['nombre_categoria','Nombre'],['vigente_desde','Desde'],['vigente_hasta','Hasta'],['salario_base','Salario base'],['auxilio_transporte','Auxilio transporte'],['otros_recargos','Recargos adicionales mensuales']].map(([k,l])=><label key={k}>{l}<input type={k.includes('vigente')?'date':k.includes('base')||k.includes('transporte')||k.includes('recargos')?'number':'text'} value={String(form[k]??'')} onChange={e=>f(k,e.target.value===''?'':(k.includes('vigente')?e.target.value:k.includes('base')||k.includes('transporte')||k.includes('recargos')?Number(e.target.value):e.target.value))}/></label>)}<div className="nomina-drawer-actions"><button className="adm-btn ghost" onClick={()=>setOpen(false)}>Cancelar</button><button className="adm-btn primary" onClick={()=>void save()}>Guardar vigencia</button></div></aside></div>}</section>;
}
