import { useEffect, useMemo, useState } from 'react';
import { apiClient } from '../../../../services/apiClient';
import { configuracionApi } from '../../../../services/configuracionApi';
import { useCompanyContext } from '../../../../context/CompanyContext';

type Area = { id: string; codigo: string; nombre: string; activo: boolean; orden: number | null };
type User = { id: string; name: string; email: string; roles: string[]; empresaIds: number[] };
type Responsibility = { id: string; proceso: string; activo: boolean; municipio_ids: number[]; area_ids: number[] };
type Municipality = { id: number; nombre_municipio?: string; nombre?: string };

const slugCode = (name: string) => name.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_|_$/g, '');

export function NominaProcesosTab() {
  const { empresaActual } = useCompanyContext();
  const [tab, setTab] = useState<'responsables' | 'areas'>('responsables');
  const [users, setUsers] = useState<User[]>([]); const [selectedUser, setSelectedUser] = useState<User | null>(null); const [search, setSearch] = useState('');
  const [areas, setAreas] = useState<Area[]>([]); const [municipios, setMunicipios] = useState<Municipality[]>([]); const [assignments, setAssignments] = useState<Responsibility[]>([]);
  const [processes, setProcesses] = useState<string[]>([]); const [municipioIds, setMunicipioIds] = useState<number[]>([]); const [areaIds, setAreaIds] = useState<number[]>([]);
  const [drawer, setDrawer] = useState(false); const [areaModal, setAreaModal] = useState(false); const [areaEdit, setAreaEdit] = useState<Area | null>(null); const [areaName, setAreaName] = useState(''); const [message, setMessage] = useState('');
  const loadAreas = async () => { if (!empresaActual) return; const r = await apiClient.get<{ data: Area[] }>('/nomina/procesos/areas', { params: { empresa_id: empresaActual.id } }); setAreas(r.data); };
  useEffect(() => { void loadAreas(); void configuracionApi.listarUsuariosAdmin().then((r) => setUsers(r)); void configuracionApi.listarMunicipios({ page: 1, limit: 500 }).then((r) => setMunicipios(r.items ?? [])); }, [empresaActual?.id]);
  const visibleUsers = useMemo(() => users.filter((u) => `${u.name} ${u.email}`.toLowerCase().includes(search.toLowerCase())), [users, search]);
  const loadAssignments = async (u: User) => { if (!empresaActual) return; const r = await apiClient.get<{ data: Responsibility[] }>('/nomina/procesos/responsabilidades', { params: { usuario_id: u.id, empresa_id: empresaActual.id } }); setAssignments(r.data); setProcesses(r.data.filter((x) => x.activo).map((x) => x.proceso)); setMunicipioIds(r.data.find((x) => x.proceso === 'COBERTURA')?.municipio_ids ?? []); setAreaIds(r.data.find((x) => x.proceso === 'ASISTENCIA')?.area_ids ?? []); };
  const openUser = async (u: User) => { setSelectedUser(u); await loadAssignments(u); setDrawer(true); };
  const save = async () => { if (!empresaActual || !selectedUser) return; for (const p of ['COBERTURA', 'ASISTENCIA', 'OPS']) { const active = processes.includes(p); await apiClient.put('/nomina/procesos/responsabilidades', { usuario_id: selectedUser.id, empresa_id: empresaActual.id, proceso: p, municipio_ids: p === 'COBERTURA' && active ? municipioIds : [], area_ids: p === 'ASISTENCIA' && active ? areaIds : [] }); } setMessage('Responsabilidad guardada.'); await loadAssignments(selectedUser); };
  const saveArea = async () => { if (!empresaActual || !areaName.trim()) return; if (areaEdit) await apiClient.patch(`/nomina/procesos/areas/${areaEdit.id}`, { nombre: areaName.trim() }); else await apiClient.post('/nomina/procesos/areas', { empresa_id: empresaActual.id, codigo: slugCode(areaName), nombre: areaName.trim() }); setAreaModal(false); setAreaEdit(null); setAreaName(''); await loadAreas(); };
  if (!empresaActual) return <div className="adm-empty">Seleccione una empresa autorizada.</div>;
  return <div className="nomina-config"><div className="adm-card"><h2>Configuración de Nómina</h2><p>Configurando: <strong>{empresaActual.nombre_empresa}</strong></p><p>Define quién participa en cada proceso y cómo se organiza la operación de nómina de esta empresa.</p><div className="cg-cat-tabs"><button className={tab === 'responsables' ? 'active' : ''} onClick={() => setTab('responsables')} type="button">Responsables</button><button className={tab === 'areas' ? 'active' : ''} onClick={() => setTab('areas')} type="button">Áreas de asistencia</button></div></div>
    {tab === 'responsables' && <div className="adm-card"><div className="nomina-section-head"><div><h3>Responsables de Nómina</h3><p>Asigne procesos y alcances sin usar identificadores técnicos.</p></div><button className="adm-btn primary" type="button" onClick={() => { setSelectedUser(null); setDrawer(true); }}>+ Configurar responsable</button></div><input aria-label="Buscar usuario" placeholder="Buscar usuario por nombre o correo..." value={search} onChange={(e) => setSearch(e.target.value)} />{visibleUsers.length === 0 ? <div className="adm-empty">No hay responsables configurados para esta empresa.</div> : <div className="nomina-responsables-list">{visibleUsers.map((u) => <button className="nomina-responsable-row" type="button" key={u.id} onClick={() => void openUser(u)}><span><strong>{u.name}</strong><small>{u.roles.join(' · ') || 'Usuario'}</small></span><span>{assignments.filter((a) => a.activo).map((a) => a.proceso).join(' · ') || 'Sin asignación'}</span><span>Editar</span></button>)}</div>}</div>}
    {tab === 'areas' && <div className="adm-card"><div className="nomina-section-head"><div><h3>Áreas de asistencia</h3><p>Configura las áreas utilizadas para reportar nómina por asistencia.</p></div><button className="adm-btn primary" type="button" onClick={() => { setAreaEdit(null); setAreaName(''); setAreaModal(true); }}>+ Nueva área</button></div>{areas.length === 0 ? <div className="adm-empty">No hay áreas de asistencia configuradas todavía.<br /><button className="adm-btn ghost" type="button" onClick={() => setAreaModal(true)}>Crear primera área</button></div> : <table className="adm-history"><thead><tr><th>Área</th><th>Código</th><th>Estado</th><th /></tr></thead><tbody>{areas.map((a) => <tr key={a.id}><td>{a.nombre}</td><td>{a.codigo}</td><td>{a.activo ? 'Activa' : 'Inactiva'}</td><td><button className="adm-btn ghost sm" type="button" onClick={() => { setAreaEdit(a); setAreaName(a.nombre); setAreaModal(true); }}>Editar</button><button className="adm-btn ghost sm" type="button" onClick={() => void apiClient.patch(`/nomina/procesos/areas/${a.id}`, { activo: !a.activo }).then(loadAreas)}>{a.activo ? 'Desactivar' : 'Reactivar'}</button></td></tr>)}</tbody></table>}</div>}
    {drawer && <div className="nomina-drawer-backdrop" role="presentation"><aside className="nomina-drawer"><button className="nomina-close" type="button" onClick={() => setDrawer(false)}>×</button><h3>{selectedUser ? 'Editar responsable' : 'Configurar responsable'}</h3><label>Usuario<input aria-label="Buscar usuario" placeholder="Buscar por nombre o correo" value={selectedUser?.name ?? search} onChange={(e) => { setSearch(e.target.value); setSelectedUser(null); }} /></label>{!selectedUser && visibleUsers.slice(0, 8).map((u) => <button className="nomina-user-option" type="button" key={u.id} onClick={() => void openUser(u)}>{u.name} · {u.email}</button>)}{selectedUser && <><p><strong>{selectedUser.name}</strong> · {selectedUser.email}</p><fieldset><legend>Procesos de Nómina</legend>{['COBERTURA', 'ASISTENCIA', 'OPS'].map((p) => <label key={p}><input type="checkbox" checked={processes.includes(p)} onChange={(e) => setProcesses((v) => e.target.checked ? [...v, p] : v.filter((x) => x !== p))} /> {p}</label>)}</fieldset>{processes.includes('COBERTURA') && <fieldset><legend>Municipios asignados</legend>{municipios.map((m) => <label key={m.id}><input type="checkbox" checked={municipioIds.includes(m.id)} onChange={(e) => setMunicipioIds((v) => e.target.checked ? [...v, m.id] : v.filter((x) => x !== m.id))} /> {m.nombre_municipio ?? m.nombre}</label>)}</fieldset>}{processes.includes('ASISTENCIA') && <fieldset><legend>Áreas asignadas</legend>{areas.filter((a) => a.activo).map((a) => <label key={a.id}><input type="checkbox" checked={areaIds.includes(Number(a.id))} onChange={(e) => setAreaIds((v) => e.target.checked ? [...v, Number(a.id)] : v.filter((x) => x !== Number(a.id)))} /> {a.nombre}</label>)}</fieldset>}<button className="adm-btn primary" type="button" onClick={() => void save()}>Guardar</button>{processes.length === 0 && <p role="status">Este usuario quedará sin responsabilidad de Nómina.</p>}</>}</aside></div>}
    {areaModal && <div className="nomina-drawer-backdrop"><div className="nomina-modal"><h3>{areaEdit ? 'Editar área' : 'Nueva área'}</h3><label>Nombre<input autoFocus value={areaName} onChange={(e) => setAreaName(e.target.value)} /></label><p>Código automático: <code>{slugCode(areaName) || '—'}</code></p><button className="adm-btn primary" type="button" onClick={() => void saveArea()}>Guardar</button><button className="adm-btn ghost" type="button" onClick={() => setAreaModal(false)}>Cancelar</button></div></div>}
    {message && <p role="status">{message}</p>}
  </div>;
}
