import { useEffect, useMemo, useState } from 'react';
import { useCompanyContext } from '../../../../context/CompanyContext';
import { saasApi, type CompanySaasHistory, type EmpresaCapabilities, type SaasModule, type SaasPlan } from '../../../../services/saasApi';
const today=()=>new Date().toISOString().slice(0,10);
type Form={codigo:string;nombre:string;descripcion:string;precio:string;moneda:string;periodicidad:string;activo:boolean;modulos:number[]};
const emptyForm:Form={codigo:'',nombre:'',descripcion:'',precio:'',moneda:'',periodicidad:'',activo:true,modulos:[]};
export function PlanesModulosTab({initialCompanyId}:{initialCompanyId:number|null}){
 const {empresasDisponibles}=useCompanyContext();const [modules,setModules]=useState<SaasModule[]>([]),[plans,setPlans]=useState<SaasPlan[]>([]),[companyId,setCompanyId]=useState<number|null>(initialCompanyId??empresasDisponibles[0]?.id??null);const [capabilities,setCapabilities]=useState<EmpresaCapabilities|null>(null),[history,setHistory]=useState<CompanySaasHistory|null>(null),[pendingPlanId,setPendingPlanId]=useState('');const [editing,setEditing]=useState<SaasPlan|null>(null),[form,setForm]=useState<Form>(emptyForm),[showForm,setShowForm]=useState(false),[message,setMessage]=useState('');
 const activePlans=useMemo(()=>plans.filter(plan=>plan.activo),[plans]);const reloadCatalog=async()=>{const [m,p]=await Promise.all([saasApi.modules(),saasApi.plans()]);setModules(m);setPlans(p);};const reloadCompany=async(id:number)=>{const [caps,hist]=await Promise.all([saasApi.capabilities(id),saasApi.history(id)]);setCapabilities(caps);setHistory(hist);setPendingPlanId(caps.suscripcion?String(caps.suscripcion.plan.id):'');};
 useEffect(()=>{void reloadCatalog();},[]);useEffect(()=>{if(initialCompanyId)setCompanyId(initialCompanyId);},[initialCompanyId]);useEffect(()=>{setCapabilities(null);setHistory(null);if(companyId)void reloadCompany(companyId);},[companyId]);
 const startPlan=(plan?:SaasPlan)=>{setEditing(plan??null);setForm(plan?{codigo:plan.codigo,nombre:plan.nombre,descripcion:plan.descripcion??'',precio:plan.precio_base??'',moneda:plan.moneda??'',periodicidad:plan.periodicidad??'',activo:plan.activo,modulos:plan.modulos.filter(x=>x.habilitado).map(x=>x.id)}:emptyForm);setShowForm(true);};
 const savePlan=async()=>{const payload={codigo:form.codigo,nombre:form.nombre,descripcion:form.descripcion||null,precio_base:form.precio===''?null:Number(form.precio),moneda:form.moneda||null,periodicidad:form.periodicidad||null,activo:form.activo,orden:editing?.orden??plans.length+1,modulo_ids:form.modulos};if(editing)await saasApi.updatePlan(editing.id,payload);else await saasApi.createPlan(payload);setShowForm(false);setMessage('Plan guardado.');await reloadCatalog();};
 const changePlan=async()=>{if(!companyId||!pendingPlanId||capabilities?.suscripcion?.plan.id===Number(pendingPlanId))return;if(!window.confirm('Cambiar el plan puede habilitar o bloquear módulos operativos. Los datos históricos no se eliminarán. ¿Continuar?'))return;await saasApi.changePlan(companyId,{plan_id:Number(pendingPlanId),estado:'ACTIVA',fecha_inicio:today(),fecha_fin:null});setMessage('Plan cambiado y suscripción anterior cerrada.');await reloadCompany(companyId);};
 const setOverride=async(module:SaasModule,value:string)=>{if(!companyId)return;if(value==='PLAN')await saasApi.clearOverride(companyId,module.id);else await saasApi.override(companyId,{modulo_id:module.id,habilitado:value==='ON',motivo:'Configuración administrativa de empresa',fecha_inicio:today(),fecha_fin:null});await reloadCompany(companyId);};
 const togglePlan=async(plan:SaasPlan)=>{await saasApi.updatePlan(plan.id,{codigo:plan.codigo,nombre:plan.nombre,descripcion:plan.descripcion,precio_base:plan.precio_base===null?null:Number(plan.precio_base),moneda:plan.moneda,periodicidad:plan.periodicidad,activo:!plan.activo,orden:plan.orden,modulo_ids:plan.modulos.filter(x=>x.habilitado).map(x=>x.id)});await reloadCatalog();};
 return <section className="cg-tab-section"><div className="cg-tab-header"><div><h2>Planes y módulos</h2><p className="cg-tab-subtitle">Plan comercial, excepciones y resultado efectivo por empresa.</p></div><button className="adm-btn primary" onClick={()=>startPlan()}>Nuevo plan</button></div>{message&&<div className="adm-notice info">{message}</div>}
 <div className="cg-form-grid"><label>Empresa<select value={companyId??''} onChange={e=>setCompanyId(Number(e.target.value))}>{empresasDisponibles.map(x=><option key={x.id} value={x.id}>{x.nombre_empresa}</option>)}</select></label><label>Nuevo plan<select value={pendingPlanId} onChange={e=>setPendingPlanId(e.target.value)}><option value="">LEGACY / SIN PLAN CONFIGURADO</option>{activePlans.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label><button className="adm-btn primary" disabled={!pendingPlanId||Number(pendingPlanId)===capabilities?.suscripcion?.plan.id} onClick={()=>void changePlan()}>Guardar / cambiar plan</button></div>
 {capabilities&&<><div className="adm-card"><h3>{capabilities.empresa.nombre}</h3><p>{capabilities.organizacion?.nombre??'Sin organización'}</p><div className="adm-kpi-row"><div className="adm-kpi neutral"><span>Plan actual</span><strong>{capabilities.suscripcion?.plan.nombre??'LEGACY / SIN PLAN CONFIGURADO'}</strong></div><div className="adm-kpi neutral"><span>Estado</span><strong>{capabilities.suscripcion?.estado??'LEGACY'}</strong></div><div className="adm-kpi neutral"><span>Vigencia</span><strong>{capabilities.suscripcion?`${capabilities.suscripcion.fecha_inicio} → ${capabilities.suscripcion.fecha_fin??'Actual'}`:'Compatibilidad activa'}</strong></div></div></div><div className="cg-table-wrap"><table className="adm-history"><thead><tr><th>Módulo</th><th>Incluido en plan</th><th>Override</th><th>Resultado efectivo</th></tr></thead><tbody>{modules.map(module=>{const override=capabilities.overrides.find(x=>x.codigo===module.codigo);const value=override?(override.habilitado?'ON':'OFF'):'PLAN';return <tr key={module.id}><td>{module.nombre}<div className="cg-secondary-cell">{module.codigo}{!module.activo?' · Inactivo global':''}</div></td><td>{capabilities.modulos_plan.includes(module.codigo)?'✓':'✕'}</td><td><select value={value} disabled={!module.activo} onChange={e=>void setOverride(module,e.target.value)}><option value="PLAN">Usar configuración del plan</option><option value="ON">Forzar habilitado</option><option value="OFF">Forzar deshabilitado</option></select></td><td><span className={`adm-badge ${capabilities.modulos[module.codigo]?'active':'inactive'}`}>{capabilities.modulos[module.codigo]?'Habilitado':'Deshabilitado'}</span></td></tr>})}</tbody></table></div></>}
 <h3>Histórico de suscripciones</h3><div className="cg-table-wrap"><table className="adm-history"><thead><tr><th>Plan</th><th>Estado</th><th>Desde</th><th>Hasta</th></tr></thead><tbody>{history?.suscripciones.length?history.suscripciones.map(x=><tr key={x.id}><td>{x.plan_nombre}</td><td>{x.estado}</td><td>{x.fecha_inicio}</td><td>{x.fecha_fin??'Actual'}</td></tr>):<tr><td colSpan={4}>Sin histórico: empresa en modo Legacy.</td></tr>}</tbody></table></div><details><summary>Histórico de overrides ({history?.overrides.length??0})</summary><div className="cg-table-wrap"><table className="adm-history"><thead><tr><th>Módulo</th><th>Configuración</th><th>Motivo</th><th>Vigencia</th></tr></thead><tbody>{history?.overrides.map(x=><tr key={x.id}><td>{x.modulo_nombre}</td><td>{x.habilitado?'Forzado habilitado':'Forzado deshabilitado'}</td><td>{x.motivo}</td><td>{x.fecha_inicio} → {x.fecha_fin??'Actual'}</td></tr>)}</tbody></table></div></details>
 <h3>Planes disponibles</h3><div className="cg-table-wrap"><table className="adm-history"><thead><tr><th>Código</th><th>Plan</th><th>Precio</th><th>Estado</th><th>Módulos</th><th></th></tr></thead><tbody>{plans.map(plan=><tr key={plan.id}><td>{plan.codigo}</td><td>{plan.nombre}</td><td>{plan.precio_base===null?'Sin precio configurado':`${plan.moneda??''} ${plan.precio_base}`}</td><td>{plan.activo?'Activo':'Inactivo'}</td><td>{plan.modulos.filter(x=>x.habilitado).length}</td><td><button className="adm-btn ghost sm" onClick={()=>startPlan(plan)}>Editar</button><button className="adm-btn ghost sm" onClick={()=>void togglePlan(plan)}>{plan.activo?'Desactivar':'Activar'}</button></td></tr>)}</tbody></table></div>
 {showForm&&<div className="adm-card"><h3>{editing?'Editar plan':'Crear plan'}</h3><div className="cg-form-grid"><label>Código *<input value={form.codigo} disabled={editing!==null} onChange={e=>setForm({...form,codigo:e.target.value.toUpperCase()})}/></label><label>Nombre *<input value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Descripción<input value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></label><label>Moneda<input maxLength={3} value={form.moneda} onChange={e=>setForm({...form,moneda:e.target.value.toUpperCase()})}/></label><label>Periodicidad<select value={form.periodicidad} onChange={e=>setForm({...form,periodicidad:e.target.value})}><option value="">Sin configurar</option>{['MENSUAL','TRIMESTRAL','SEMESTRAL','ANUAL','PERSONALIZADA'].map(x=><option key={x}>{x}</option>)}</select></label><label>Precio opcional<input type="number" min="0" value={form.precio} onChange={e=>setForm({...form,precio:e.target.value})}/></label></div><div className="cg-checkbox-grid">{modules.filter(x=>x.activo).map(module=><label key={module.id}><input type="checkbox" checked={form.modulos.includes(module.id)} onChange={e=>setForm({...form,modulos:e.target.checked?[...form.modulos,module.id]:form.modulos.filter(id=>id!==module.id)})}/>{module.nombre}</label>)}</div><button className="adm-btn primary" disabled={!form.codigo.trim()||!form.nombre.trim()} onClick={()=>void savePlan()}>Guardar plan</button><button className="adm-btn secondary" onClick={()=>setShowForm(false)}>Cancelar</button></div>}</section>;
}
