import { apiClient } from './apiClient';
import type { ApiResponse } from '../types/api.types';
import { env } from '../config/env'; import { getAuthToken } from './tokenStorage';
export type PersonalCoverageStatus = 'COMPLETA' | 'FALTANTE' | 'EXCEDENTE' | 'SIN_PERSONAL_REQUERIDO' | 'SIN_SERVICIO_FOCALIZADO' | 'FUERA_DE_RANGO' | 'MODALIDAD_SIN_REGLA';
export type Institution = { id: string; institucion_id: string; institucion: string | null; dane?: string | null; sede_id: string | null; sede: string | null; codigo_dane_sede?: string | null; municipio_id: string | null; municipio: string | null; modalidad_id: string | null; modalidad: string | null; periodo_focalizacion: { id: string; nombre: string | null; anio: number; mes: number }; rector: { id?: string; nombre: string } | null; gestor: { id: string; nombre: string | null } | null; gestores_parciales: Array<{ id: string; nombre: string | null }>; asignacion_gestor: 'MUNICIPIO_COMPLETO' | 'PERSONAL_SELECCIONADO' | null; matriculados: { primaria: number | null; secundaria: number | null; total: number | null; fuente: string }; techo: { primaria: number | null; secundaria: number | null; total: number | null; fuente: string }; focalizacion: { primaria: number | null; secundaria: number | null; total: number | null; fuente: string }; ejecucion: { raciones_entregadas: number | null; fuente: string | null }; indicadores: { cobertura_programada: number | null; utilizacion_techo: number | null; cobertura_ejecutada: number | null; diferencia_matricula_focalizacion: number | null; diferencia_focalizacion_techo: number | null }; cupos: { primaria: number | null; secundaria: number | null; total: number | null }; atencion: { primaria: number | null; secundaria: number | null; total: number | null }; cobertura: { porcentaje: number | null }; personal_cobertura: { tipo_regla: string | null; raciones_base: number; multiplicador: number; raciones_calculadas: number; rango_desde: number | null; rango_hasta: number | null; requeridas: number | null; vinculadas: number; diferencia: number | null; estado: PersonalCoverageStatus; mensaje: string | null; advertencia: string | null }; estado: string; activo: boolean; jornada: string | null; zona: string | null; vigencia: { desde: string | null; hasta: string | null }; sedes?: number; matricula?: number; focalizados?: number };
export type InstitutionOption = { id: string; nombre: string; municipio_id?: string | null; institucion_id?: string | null };
export type InstitutionPeriod = InstitutionOption & { anio: number; mes: number; etiqueta?: string; desde?: string | null; hasta?: string | null };
export type InstitutionResult = { items: Institution[]; total: number; page: number; page_size: number; total_pages: number; summary: { instituciones: number; sedes: number; combinaciones: number; matriculados: number; techo_autorizado: number; cupos_focalizados: number; cupos: number; manipuladoras_requeridas: number; manipuladoras_vinculadas: number; faltantes: number; excedentes: number; faltante_personal: number; excedente_personal: number; sin_personal_requerido: number; sin_servicio_focalizado: number; personal_sin_servicio: number; sedes_fuera_rango: number; modalidades_sin_regla: number; cobertura_estudiantil_global: number | null; utilizacion_techo_global: number | null; cobertura_ejecutada_global: number | null }; filter_options: { focalizaciones: InstitutionPeriod[]; municipios: InstitutionOption[]; instituciones: InstitutionOption[]; sedes: InstitutionOption[]; modalidades: InstitutionOption[]; rectores: InstitutionOption[]; gestores: InstitutionOption[]; estados: InstitutionOption[] }; contrato_id: number };
export type SimatResult = { items: Record<string, unknown>[]; total: number; page: number; limit: number };
export const operacionApi = {
  institutions: (params: Record<string, string | number | undefined>) => apiClient.get<ApiResponse<InstitutionResult>>('/operacion/instituciones', { params }),
  updateFocalizacion: (id: string, body: Record<string, unknown>) => apiClient.patch<ApiResponse<unknown>>(`/operacion/instituciones/focalizaciones/${id}`, body),
  institution: (id: string) => apiClient.get<ApiResponse<Institution & { sedes?: Array<{ id:string; nombre:string; codigo_dane_sede:string|null; consecutivo:string|null; zona_sede:string|null; activo:boolean }> }>>(`/operacion/instituciones/${id}`),
  createSede: (institutionId:string, body:unknown) => apiClient.post<ApiResponse<unknown>>(`/operacion/instituciones/${institutionId}/sedes`, body),
  updateSede: (id:string, body:unknown) => apiClient.patch<ApiResponse<unknown>>(`/operacion/sedes/${id}`, body),
  simat: (params: Record<string, string | number | undefined>) => apiClient.get<ApiResponse<SimatResult>>('/operacion/simat', { params }),
  validateImport: (file: File, contratoId?: number) => { const body = new FormData(); body.append('file', file); if (contratoId) body.append('contrato_id', String(contratoId)); return apiClient.post<ApiResponse<{ importacion_id: string|null; resumen: Record<string, number> }>>('/operacion/simat/import/validate', body); },
  confirmImport: (file: File, contratoId?: number) => { const body = new FormData(); body.append('file', file); if (contratoId) body.append('contrato_id', String(contratoId)); return apiClient.post<ApiResponse<{ importacion_id: string; resumen: Record<string, number> }>>('/operacion/simat/import', body); },
  exportSimat: async (params: Record<string,string|number|undefined>={}) => { const url=new URL(`${env.apiUrl}/operacion/simat/export`); Object.entries(params).forEach(([k,v])=>v!==undefined&&url.searchParams.set(k,String(v))); const response=await fetch(url,{headers:{Authorization:`Bearer ${getAuthToken()??''}`}}); if(!response.ok)throw new Error('No fue posible exportar SIMAT.'); const blob=await response.blob(); const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='simat-filtrado.xlsx';link.click();URL.revokeObjectURL(link.href); },
};
