CREATE TABLE IF NOT EXISTS auditoria_eventos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint REFERENCES usuarios(id),
  empresa_id bigint REFERENCES empresas(id),
  contrato_id bigint REFERENCES contratos(id),
  modulo text NOT NULL,
  entidad text NOT NULL,
  entidad_id text NOT NULL,
  accion text NOT NULL,
  descripcion text NOT NULL,
  datos_anteriores jsonb,
  datos_nuevos jsonb,
  ip_address text,
  user_agent text,
  fecha_evento timestamp DEFAULT NOW() NOT NULL,
  created_at timestamp DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_usuario_id
  ON auditoria_eventos (usuario_id);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_empresa_id
  ON auditoria_eventos (empresa_id);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_contrato_id
  ON auditoria_eventos (contrato_id);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_modulo
  ON auditoria_eventos (modulo);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_entidad
  ON auditoria_eventos (entidad);

CREATE INDEX IF NOT EXISTS idx_auditoria_eventos_fecha_evento
  ON auditoria_eventos (fecha_evento);
