CREATE EXTENSION IF NOT EXISTS unaccent;

-- Phase 22.1 - Focalizacion historica e importacion operativa PAE
-- No elimina historicos existentes. Amplia tablas heredadas y agrega tablas faltantes.

ALTER TABLE IF EXISTS focalizacion_cargas
  ADD COLUMN IF NOT EXISTS fecha_recepcion date NULL,
  ADD COLUMN IF NOT EXISTS fecha_inicio_vigencia date NULL,
  ADD COLUMN IF NOT EXISTS fecha_fin_vigencia date NULL,
  ADD COLUMN IF NOT EXISTS fecha_importacion timestamp NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS archivo_mime_type text NULL,
  ADD COLUMN IF NOT EXISTS archivo_sha256 text NULL,
  ADD COLUMN IF NOT EXISTS storage_bucket text NULL,
  ADD COLUMN IF NOT EXISTS storage_path text NULL,
  ADD COLUMN IF NOT EXISTS archivo_bytes bytea NULL,
  ADD COLUMN IF NOT EXISTS total_filas integer NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS filas_procesadas integer NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS filas_alerta integer NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS filas_error integer NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS resumen_json jsonb NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS created_by bigint NULL REFERENCES usuarios(id);

CREATE INDEX IF NOT EXISTS idx_focalizacion_cargas_sha256
  ON focalizacion_cargas(contrato_id, archivo_sha256, fecha_inicio_vigencia, fecha_fin_vigencia);

ALTER TABLE IF EXISTS focalizacion_preliminar
  ADD COLUMN IF NOT EXISTS techo_primaria integer NULL,
  ADD COLUMN IF NOT EXISTS techo_secundaria integer NULL,
  ADD COLUMN IF NOT EXISTS techo_total integer NULL,
  ADD COLUMN IF NOT EXISTS fila_origen integer NULL,
  ADD COLUMN IF NOT EXISTS estado_procesamiento text NULL DEFAULT 'PENDIENTE',
  ADD COLUMN IF NOT EXISTS resultado_comparacion text NULL,
  ADD COLUMN IF NOT EXISTS mensaje_resultado text NULL,
  ADD COLUMN IF NOT EXISTS institucion_id_resuelta bigint NULL REFERENCES instituciones(id),
  ADD COLUMN IF NOT EXISTS sede_id_resuelta bigint NULL REFERENCES sedes(id),
  ADD COLUMN IF NOT EXISTS modalidad_id_resuelta bigint NULL REFERENCES modalidades(id),
  ADD COLUMN IF NOT EXISTS focalizacion_vigencia_id bigint NULL,
  ADD COLUMN IF NOT EXISTS cobertura_requerida integer NULL,
  ADD COLUMN IF NOT EXISTS fila_metadata jsonb NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_focalizacion_preliminar_carga_estado
  ON focalizacion_preliminar(carga_id, estado_procesamiento, fila_origen);

CREATE TABLE IF NOT EXISTS modalidad_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modalidad_id bigint NOT NULL REFERENCES modalidades(id) ON DELETE CASCADE,
  alias text NOT NULL,
  alias_normalizado text NOT NULL,
  activo boolean NOT NULL DEFAULT TRUE,
  created_at timestamp NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS modalidad_aliases
  ADD COLUMN IF NOT EXISTS alias_normalizado text;

CREATE UNIQUE INDEX IF NOT EXISTS uq_modalidad_alias_activo
  ON modalidad_aliases(modalidad_id, alias_normalizado)
  WHERE activo = TRUE;

CREATE TABLE IF NOT EXISTS instituciones_identidad_historial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  institucion_id bigint NOT NULL REFERENCES instituciones(id) ON DELETE CASCADE,
  nombre_original_fuente text NOT NULL,
  nombre_normalizado text NOT NULL,
  nombre_visible text NOT NULL,
  codigo_dane text NULL,
  vigente_desde date NOT NULL,
  vigente_hasta date NULL,
  origen text NOT NULL DEFAULT 'ARCHIVO',
  archivo_origen_id bigint NULL REFERENCES focalizacion_cargas(id),
  usuario_id bigint NULL REFERENCES usuarios(id),
  created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_instituciones_identidad_historial_institucion
  ON instituciones_identidad_historial(institucion_id, vigente_desde DESC, created_at DESC);

CREATE TABLE IF NOT EXISTS sedes_identidad_historial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sede_id bigint NOT NULL REFERENCES sedes(id) ON DELETE CASCADE,
  nombre_original_fuente text NOT NULL,
  nombre_normalizado text NOT NULL,
  nombre_visible text NOT NULL,
  codigo_dane text NULL,
  consecutivo_sede text NULL,
  vigente_desde date NOT NULL,
  vigente_hasta date NULL,
  origen text NOT NULL DEFAULT 'ARCHIVO',
  archivo_origen_id bigint NULL REFERENCES focalizacion_cargas(id),
  usuario_id bigint NULL REFERENCES usuarios(id),
  created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sedes_identidad_historial_sede
  ON sedes_identidad_historial(sede_id, vigente_desde DESC, created_at DESC);

CREATE TABLE IF NOT EXISTS sede_institucion_historial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sede_id bigint NOT NULL REFERENCES sedes(id) ON DELETE CASCADE,
  institucion_id bigint NOT NULL REFERENCES instituciones(id),
  vigente_desde date NOT NULL,
  vigente_hasta date NULL,
  origen text NOT NULL DEFAULT 'ARCHIVO',
  archivo_origen_id bigint NULL REFERENCES focalizacion_cargas(id),
  motivo text NULL,
  created_at timestamp NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sede_institucion_historial_activa
  ON sede_institucion_historial(sede_id)
  WHERE vigente_hasta IS NULL;

CREATE TABLE IF NOT EXISTS focalizacion_vigencias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id bigint NOT NULL REFERENCES contratos(id),
  municipio_id bigint NULL REFERENCES municipios(id),
  institucion_id bigint NOT NULL REFERENCES instituciones(id),
  sede_id bigint NOT NULL REFERENCES sedes(id),
  modalidad_id bigint NOT NULL REFERENCES modalidades(id),
  carga_id bigint NULL REFERENCES focalizacion_cargas(id),
  preliminar_id bigint NULL REFERENCES focalizacion_preliminar(id),
  regla_config_id bigint NULL,
  focalizacion_total integer NOT NULL,
  focalizacion_primaria integer NULL,
  focalizacion_secundaria integer NULL,
  techo_total integer NULL,
  techo_primaria integer NULL,
  techo_secundaria integer NULL,
  vigente_desde date NOT NULL,
  vigente_hasta date NULL,
  fecha_recepcion date NULL,
  cobertura_requerida integer NULL,
  cobertura_estado text NOT NULL DEFAULT 'PENDIENTE',
  origen text NOT NULL DEFAULT 'ARCHIVO',
  motivo text NULL,
  observacion text NULL,
  soporte_storage_bucket text NULL,
  soporte_storage_path text NULL,
  activo boolean NOT NULL DEFAULT TRUE,
  valor_anterior_id bigint NULL REFERENCES focalizacion_vigencias(id),
  created_by bigint NULL REFERENCES usuarios(id),
  created_at timestamp NOT NULL DEFAULT NOW(),
  updated_at timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_focalizacion_vigencias_lookup
  ON focalizacion_vigencias(contrato_id, sede_id, modalidad_id, vigente_desde DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_focalizacion_vigencias_activas
  ON focalizacion_vigencias(contrato_id, activo, sede_id, modalidad_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'focalizacion_preliminar'
      AND column_name = 'focalizacion_vigencia_id'
  ) THEN
    BEGIN
      ALTER TABLE focalizacion_preliminar
        ADD CONSTRAINT fk_focalizacion_preliminar_vigencia
        FOREIGN KEY (focalizacion_vigencia_id)
        REFERENCES focalizacion_vigencias(id);
    EXCEPTION
      WHEN duplicate_object THEN
        NULL;
    END;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS calculadora_personal_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version integer NOT NULL DEFAULT 1,
  nombre varchar(120) NOT NULL,
  descripcion text,
  metodo varchar(20) NOT NULL DEFAULT 'rangos'
    CHECK (metodo IN ('formula','rangos')),
  modalidad varchar(50),
  modalidad_id bigint NULL REFERENCES modalidades(id),
  contrato_id bigint NULL REFERENCES contratos(id),
  dominio_calculo varchar(40) NOT NULL DEFAULT 'GENERAL',
  factor_previo numeric(12, 4),
  formula text,
  variables_permitidas text[] NOT NULL DEFAULT ARRAY['cupos','base','minimo','divisor','modalidad','contrato_id'],
  personal_minimo integer NOT NULL DEFAULT 0,
  personal_maximo integer,
  regla_redondeo varchar(20) NOT NULL DEFAULT 'ceil'
    CHECK (regla_redondeo IN ('nearest','floor','ceil','none')),
  config_padre_id bigint REFERENCES calculadora_personal_config(id),
  vigencia_desde date NOT NULL DEFAULT CURRENT_DATE,
  vigencia_hasta date,
  estado varchar(20) NOT NULL DEFAULT 'activo'
    CHECK (estado IN ('activo','inactivo')),
  observacion_cambio text,
  usuario_creacion bigint NOT NULL REFERENCES usuarios(id),
  usuario_modificacion bigint REFERENCES usuarios(id),
  creado_en timestamp NOT NULL DEFAULT NOW(),
  modificado_en timestamp NOT NULL DEFAULT NOW()
);

ALTER TABLE IF EXISTS calculadora_personal_config
  ADD COLUMN IF NOT EXISTS modalidad_id bigint NULL REFERENCES modalidades(id),
  ADD COLUMN IF NOT EXISTS contrato_id bigint NULL REFERENCES contratos(id),
  ADD COLUMN IF NOT EXISTS dominio_calculo varchar(40) NOT NULL DEFAULT 'GENERAL',
  ADD COLUMN IF NOT EXISTS factor_previo numeric(12, 4);

CREATE TABLE IF NOT EXISTS calculadora_personal_rangos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id bigint NOT NULL REFERENCES calculadora_personal_config(id) ON DELETE CASCADE,
  desde integer NOT NULL,
  hasta integer,
  personal_requerido integer NOT NULL,
  orden integer NOT NULL DEFAULT 0,
  estado varchar(20) NOT NULL DEFAULT 'activo'
    CHECK (estado IN ('activo','inactivo')),
  creado_en timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_calc_personal_estado ON calculadora_personal_config(estado);
CREATE INDEX IF NOT EXISTS idx_calc_personal_modalidad ON calculadora_personal_config(modalidad);
CREATE INDEX IF NOT EXISTS idx_calc_personal_modalidad_id ON calculadora_personal_config(modalidad_id);
CREATE INDEX IF NOT EXISTS idx_calc_personal_contrato_id ON calculadora_personal_config(contrato_id);
CREATE INDEX IF NOT EXISTS idx_calc_personal_dominio ON calculadora_personal_config(dominio_calculo);
CREATE INDEX IF NOT EXISTS idx_calc_personal_vigencia ON calculadora_personal_config(vigencia_desde, vigencia_hasta);
CREATE INDEX IF NOT EXISTS idx_calc_rangos_config_id ON calculadora_personal_rangos(config_id);
CREATE INDEX IF NOT EXISTS idx_calc_rangos_estado ON calculadora_personal_rangos(estado, config_id);

DROP INDEX IF EXISTS uq_calc_personal_activo_modalidad;
CREATE UNIQUE INDEX IF NOT EXISTS uq_calc_personal_activo_contexto
  ON calculadora_personal_config(
    COALESCE(contrato_id, 0),
    COALESCE(modalidad_id, 0),
    COALESCE(dominio_calculo, 'GENERAL'),
    estado
  )
  WHERE estado = 'activo';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'calculadora_personal_config'
  ) THEN
    BEGIN
      ALTER TABLE focalizacion_vigencias
        ADD CONSTRAINT fk_focalizacion_vigencias_regla_config
        FOREIGN KEY (regla_config_id)
        REFERENCES calculadora_personal_config(id);
    EXCEPTION
      WHEN duplicate_object THEN
        NULL;
    END;
  END IF;
END $$;

ALTER TABLE IF EXISTS focalizacion_final
  ADD COLUMN IF NOT EXISTS vigente_desde date NULL,
  ADD COLUMN IF NOT EXISTS vigente_hasta date NULL,
  ADD COLUMN IF NOT EXISTS cobertura_requerida integer NULL,
  ADD COLUMN IF NOT EXISTS cobertura_estado text NULL DEFAULT 'PENDIENTE';

WITH contratos_cobertura AS (
  SELECT
    c.id AS contrato_id,
    c.numero_contrato,
    COALESCE(c.fecha_inicio::date, CURRENT_DATE) AS vigencia_desde,
    COALESCE(c.fecha_final_real::date, c.fecha_final_estimada::date) AS vigencia_hasta
  FROM contratos c
  WHERE COALESCE(c.aplica_cobertura, FALSE) = TRUE
),
seed_configs AS (
  INSERT INTO calculadora_personal_config (
    version,
    nombre,
    descripcion,
    metodo,
    modalidad,
    modalidad_id,
    contrato_id,
    dominio_calculo,
    factor_previo,
    formula,
    variables_permitidas,
    personal_minimo,
    personal_maximo,
    regla_redondeo,
    config_padre_id,
    vigencia_desde,
    vigencia_hasta,
    estado,
    observacion_cambio,
    usuario_creacion,
    usuario_modificacion,
    creado_en,
    modificado_en
  )
  SELECT
    1,
    'Cobertura PAE ' || cc.numero_contrato || ' - ' || m.codigo_original,
    'Regla base de cobertura PAE migrada en phase-22-1',
    'rangos',
    m.codigo_original,
    m.id,
    cc.contrato_id,
    'COBERTURA_PAE',
    CASE WHEN m.codigo_original = 'CAARES' THEN 4 ELSE NULL END,
    NULL,
    ARRAY['cupos','total','cupos_calculo','contrato_id']::text[],
    0,
    NULL,
    'ceil',
    NULL,
    cc.vigencia_desde,
    cc.vigencia_hasta,
    'activo',
    'Semilla inicial de reglas de cobertura PAE',
    (SELECT id FROM usuarios ORDER BY id ASC LIMIT 1),
    (SELECT id FROM usuarios ORDER BY id ASC LIMIT 1),
    NOW(),
    NOW()
  FROM contratos_cobertura cc
  CROSS JOIN modalidades m
  WHERE m.codigo_original IN ('CAA', 'CAA-JU', 'CAARES', 'CAJM/JT-RI', 'CAJU-RI')
    AND NOT EXISTS (
      SELECT 1
      FROM calculadora_personal_config existing
      WHERE COALESCE(existing.dominio_calculo, 'GENERAL') = 'COBERTURA_PAE'
        AND existing.contrato_id = cc.contrato_id
        AND existing.modalidad_id = m.id
        AND existing.estado = 'activo'
    )
  RETURNING id, contrato_id, modalidad_id, modalidad
)
SELECT 1;

INSERT INTO calculadora_personal_rangos (config_id, desde, hasta, personal_requerido, orden, estado)
SELECT config.id,
       ranges.desde,
       ranges.hasta,
       ranges.personal_requerido,
       ranges.orden,
       'activo'
FROM calculadora_personal_config config
JOIN modalidades m ON m.id = config.modalidad_id
JOIN LATERAL (
  SELECT *
  FROM (
    VALUES
      ('CAA', 0, 60, 1, 1),
      ('CAA', 61, 150, 2, 2),
      ('CAA', 151, 300, 3, 3),
      ('CAA', 301, 500, 4, 4),
      ('CAA', 501, 750, 5, 5),
      ('CAA', 751, 1000, 6, 6),
      ('CAA', 1001, 1500, 7, 7),
      ('CAA-JU', 0, 60, 1, 1),
      ('CAA-JU', 61, 150, 2, 2),
      ('CAA-JU', 151, 300, 3, 3),
      ('CAA-JU', 301, 500, 4, 4),
      ('CAA-JU', 501, 750, 5, 5),
      ('CAA-JU', 751, 1000, 6, 6),
      ('CAA-JU', 1001, 1500, 7, 7),
      ('CAARES', 0, 60, 1, 1),
      ('CAARES', 61, 150, 2, 2),
      ('CAARES', 151, 300, 3, 3),
      ('CAARES', 301, 500, 4, 4),
      ('CAARES', 501, 750, 5, 5),
      ('CAARES', 751, 1000, 6, 6),
      ('CAARES', 1001, 1300, 7, 7),
      ('CAARES', 1301, 1600, 8, 8),
      ('CAARES', 1601, 1900, 9, 9),
      ('CAARES', 1901, 2200, 10, 10),
      ('CAARES', 2201, 2500, 11, 11),
      ('CAJM/JT-RI', 0, 100, 0, 1),
      ('CAJM/JT-RI', 101, 300, 1, 2),
      ('CAJM/JT-RI', 301, 500, 2, 3),
      ('CAJM/JT-RI', 501, 800, 3, 4),
      ('CAJM/JT-RI', 801, NULL, 4, 5),
      ('CAJU-RI', 0, 100, 0, 1),
      ('CAJU-RI', 101, 300, 1, 2),
      ('CAJU-RI', 301, 500, 2, 3),
      ('CAJU-RI', 501, 800, 3, 4),
      ('CAJU-RI', 801, NULL, 4, 5)
  ) AS seeded(codigo_original, desde, hasta, personal_requerido, orden)
  WHERE seeded.codigo_original = m.codigo_original
) AS ranges ON TRUE
WHERE COALESCE(config.dominio_calculo, 'GENERAL') = 'COBERTURA_PAE'
  AND config.estado = 'activo'
  AND NOT EXISTS (
    SELECT 1
    FROM calculadora_personal_rangos existing
    WHERE existing.config_id = config.id
      AND existing.desde = ranges.desde
      AND existing.hasta IS NOT DISTINCT FROM ranges.hasta
      AND existing.personal_requerido = ranges.personal_requerido
  );

INSERT INTO modalidad_aliases (modalidad_id, alias, alias_normalizado)
SELECT DISTINCT ON (m.id, upper(regexp_replace(unaccent(alias.alias), '[^A-Za-z0-9]+', ' ', 'g')))
  m.id,
  alias.alias,
  upper(regexp_replace(unaccent(alias.alias), '[^A-Za-z0-9]+', ' ', 'g'))
FROM modalidades m
JOIN (
  VALUES
    ('CAA-JU', 'CAA JU'),
    ('CAA-JU', 'CAA - JU'),
    ('CAJU-RI', 'CAJU RI'),
    ('CAJU-RI', 'CAJU - RI'),
    ('CAJM/JT-RI', 'CAJM JT RI'),
    ('CAJM/JT-RI', 'CAJM/JT RI')
) AS alias(codigo_original, alias)
  ON m.codigo_original = alias.codigo_original
ORDER BY m.id, upper(regexp_replace(unaccent(alias.alias), '[^A-Za-z0-9]+', ' ', 'g')), alias.alias
ON CONFLICT DO NOTHING;