ALTER TABLE contratos
  ADD COLUMN IF NOT EXISTS fecha_final_estimada DATE NULL,
  ADD COLUMN IF NOT EXISTS fecha_final_real DATE NULL,
  ADD COLUMN IF NOT EXISTS estado_contractual TEXT NULL,
  ADD COLUMN IF NOT EXISTS contrato_padre_id BIGINT NULL,
  ADD COLUMN IF NOT EXISTS observaciones TEXT NULL;

ALTER TABLE contratos
  ALTER COLUMN fecha_finalizacion DROP NOT NULL;

UPDATE contratos
SET fecha_final_estimada = COALESCE(fecha_final_estimada, fecha_finalizacion)
WHERE fecha_final_estimada IS NULL;

UPDATE contratos
SET estado_contractual = CASE
  WHEN COALESCE(activo, TRUE) = FALSE THEN 'BORRADOR'
  WHEN fecha_inicio > CURRENT_DATE THEN 'PENDIENTE_INICIO'
  ELSE 'ACTIVO'
END
WHERE estado_contractual IS NULL;

ALTER TABLE contratos
  ALTER COLUMN estado_contractual SET DEFAULT 'BORRADOR';

ALTER TABLE contratos
  ALTER COLUMN estado_contractual SET NOT NULL;

ALTER TABLE contratos
  DROP CONSTRAINT IF EXISTS chk_contratos_estado_contractual;

ALTER TABLE contratos
  ADD CONSTRAINT chk_contratos_estado_contractual CHECK (
    estado_contractual IN (
      'BORRADOR',
      'PENDIENTE_INICIO',
      'ACTIVO',
      'PRORROGADO',
      'SUSPENDIDO',
      'FINALIZADO',
      'LIQUIDADO',
      'ANULADO'
    )
  );

CREATE INDEX IF NOT EXISTS idx_contratos_estado_contractual
  ON contratos (estado_contractual);

ALTER TABLE contratos
  DROP CONSTRAINT IF EXISTS fk_contratos_contrato_padre;

ALTER TABLE contratos
  ADD CONSTRAINT fk_contratos_contrato_padre
  FOREIGN KEY (contrato_padre_id) REFERENCES contratos(id);

CREATE INDEX IF NOT EXISTS idx_contratos_contrato_padre_id
  ON contratos (contrato_padre_id);

ALTER TABLE tipos_documentos
  ADD COLUMN IF NOT EXISTS alcance TEXT NOT NULL DEFAULT 'GENERAL',
  ADD COLUMN IF NOT EXISTS tiene_vencimiento BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS vigencia_dias_default INTEGER NULL,
  ADD COLUMN IF NOT EXISTS requiere_revision BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS criticidad TEXT NOT NULL DEFAULT 'MEDIA',
  ADD COLUMN IF NOT EXISTS bloquea_creacion BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS bloquea_inicio BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS bloquea_ejecucion BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS bloquea_cierre BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS dias_alerta_amarilla INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS dias_alerta_naranja INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS dias_alerta_roja INTEGER NOT NULL DEFAULT 7;

UPDATE tipos_documentos
SET tiene_vencimiento = COALESCE(requiere_fecha_vencimiento, FALSE)
WHERE tiene_vencimiento = FALSE
  AND COALESCE(requiere_fecha_vencimiento, FALSE) = TRUE;

ALTER TABLE tipos_documentos
  DROP CONSTRAINT IF EXISTS chk_tipos_documentos_alcance;

ALTER TABLE tipos_documentos
  ADD CONSTRAINT chk_tipos_documentos_alcance CHECK (
    alcance IN (
      'GENERAL',
      'ORGANIZACION',
      'EMPRESA_JURIDICA',
      'CONTRATO',
      'PERSONA',
      'VINCULACION'
    )
  );

ALTER TABLE tipos_documentos
  DROP CONSTRAINT IF EXISTS chk_tipos_documentos_criticidad;

ALTER TABLE tipos_documentos
  ADD CONSTRAINT chk_tipos_documentos_criticidad CHECK (
    criticidad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')
  );

CREATE TABLE IF NOT EXISTS contrato_eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id BIGINT NOT NULL REFERENCES contratos(id),
  tipo_evento TEXT NOT NULL,
  fecha_evento DATE NOT NULL,
  fecha_efecto_desde DATE NULL,
  fecha_efecto_hasta DATE NULL,
  descripcion TEXT NULL,
  motivo TEXT NULL,
  documento_soporte_id BIGINT NULL,
  usuario_creador_id BIGINT NULL REFERENCES usuarios(id),
  datos_anteriores JSONB NULL,
  datos_posteriores JSONB NULL,
  estado_evento TEXT NOT NULL DEFAULT 'ACTIVO',
  motivo_anulacion TEXT NULL,
  anulado_por_usuario_id BIGINT NULL REFERENCES usuarios(id),
  anulado_at TIMESTAMP NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_contrato_eventos_tipo CHECK (
    tipo_evento IN (
      'CREACION',
      'ACTA_INICIO',
      'PRORROGA',
      'ADICION',
      'OTROSI',
      'MODIFICACION',
      'SUSPENSION',
      'REINICIO',
      'TERMINACION',
      'LIQUIDACION',
      'CAMBIO_REPRESENTANTE',
      'CAMBIO_SUPERVISOR',
      'CAMBIO_COBERTURA',
      'OTRO'
    )
  ),
  CONSTRAINT chk_contrato_eventos_estado CHECK (
    estado_evento IN ('ACTIVO', 'ANULADO')
  )
);

CREATE INDEX IF NOT EXISTS idx_contrato_eventos_contrato_fecha
  ON contrato_eventos (contrato_id, fecha_evento DESC, id DESC);

CREATE TABLE IF NOT EXISTS contrato_documento_requisitos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id BIGINT NOT NULL REFERENCES contratos(id),
  tipo_documento_id BIGINT NULL REFERENCES tipos_documentos(id),
  categoria TEXT NOT NULL DEFAULT 'EJECUCION',
  codigo_requisito TEXT NULL,
  nombre_requisito TEXT NOT NULL,
  descripcion TEXT NULL,
  obligatorio BOOLEAN NOT NULL DEFAULT TRUE,
  criticidad TEXT NOT NULL DEFAULT 'MEDIA',
  bloquea_creacion BOOLEAN NOT NULL DEFAULT FALSE,
  bloquea_inicio BOOLEAN NOT NULL DEFAULT FALSE,
  bloquea_ejecucion BOOLEAN NOT NULL DEFAULT FALSE,
  bloquea_cierre BOOLEAN NOT NULL DEFAULT FALSE,
  solo_alerta BOOLEAN NOT NULL DEFAULT FALSE,
  responsable TEXT NULL,
  plazo_regularizacion_dias INTEGER NULL,
  orden INTEGER NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_contrato_documento_requisitos_categoria CHECK (
    categoria IN (
      'CREACION_EMPRESA_JURIDICA',
      'INICIO_CONTRATO',
      'EJECUCION',
      'CIERRE'
    )
  ),
  CONSTRAINT chk_contrato_documento_requisitos_criticidad CHECK (
    criticidad IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_contrato_documento_requisitos_nombre
  ON contrato_documento_requisitos (contrato_id, nombre_requisito);

CREATE INDEX IF NOT EXISTS idx_contrato_documento_requisitos_contrato
  ON contrato_documento_requisitos (contrato_id, categoria, activo);

CREATE TABLE IF NOT EXISTS documentos_contrato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id BIGINT NOT NULL REFERENCES contratos(id),
  requisito_id BIGINT NULL REFERENCES contrato_documento_requisitos(id),
  tipo_documento_id BIGINT NOT NULL REFERENCES tipos_documentos(id),
  categoria TEXT NOT NULL DEFAULT 'EJECUCION',
  archivo_path TEXT NULL,
  storage_bucket TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  nombre_original TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  tamano_bytes BIGINT NOT NULL,
  fecha_expedicion DATE NULL,
  fecha_vencimiento DATE NULL,
  fecha_carga TIMESTAMP NOT NULL DEFAULT NOW(),
  vigencia_dias_configurada INTEGER NULL,
  version INTEGER NOT NULL DEFAULT 1,
  documento_reemplaza_id BIGINT NULL REFERENCES documentos_contrato(id),
  es_vigente BOOLEAN NOT NULL DEFAULT TRUE,
  estado_revision TEXT NOT NULL DEFAULT 'PENDIENTE',
  motivo_devolucion TEXT NULL,
  revisado_por_usuario_id BIGINT NULL REFERENCES usuarios(id),
  revisado_at TIMESTAMP NULL,
  observaciones TEXT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_documentos_contrato_categoria CHECK (
    categoria IN (
      'CREACION_EMPRESA_JURIDICA',
      'INICIO_CONTRATO',
      'EJECUCION',
      'CIERRE'
    )
  ),
  CONSTRAINT chk_documentos_contrato_estado_revision CHECK (
    estado_revision IN ('PENDIENTE', 'EN_REVISION', 'APROBADO', 'DEVUELTO', 'ANULADO')
  )
);

CREATE INDEX IF NOT EXISTS idx_documentos_contrato_contrato
  ON documentos_contrato (contrato_id, categoria, fecha_carga DESC);

CREATE INDEX IF NOT EXISTS idx_documentos_contrato_tipo
  ON documentos_contrato (tipo_documento_id, contrato_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_documentos_contrato_requisito_vigente
  ON documentos_contrato (contrato_id, requisito_id)
  WHERE requisito_id IS NOT NULL AND es_vigente = TRUE AND activo = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_documentos_contrato_tipo_vigente_sin_requisito
  ON documentos_contrato (contrato_id, tipo_documento_id)
  WHERE requisito_id IS NULL AND es_vigente = TRUE AND activo = TRUE;

ALTER TABLE contrato_eventos
  DROP CONSTRAINT IF EXISTS fk_contrato_eventos_documento_soporte;

ALTER TABLE contrato_eventos
  ADD CONSTRAINT fk_contrato_eventos_documento_soporte
  FOREIGN KEY (documento_soporte_id) REFERENCES documentos_contrato(id);

CREATE TABLE IF NOT EXISTS contrato_excepciones_documentales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id BIGINT NOT NULL REFERENCES contratos(id),
  requisito_id BIGINT NULL REFERENCES contrato_documento_requisitos(id),
  documento_id BIGINT NULL REFERENCES documentos_contrato(id),
  motivo TEXT NOT NULL,
  usuario_autorizador_id BIGINT NOT NULL REFERENCES usuarios(id),
  fecha_autorizacion TIMESTAMP NOT NULL DEFAULT NOW(),
  fecha_limite_regularizacion DATE NOT NULL,
  soporte_documento_id BIGINT NULL REFERENCES documentos_contrato(id),
  estado TEXT NOT NULL DEFAULT 'ABIERTA',
  observaciones TEXT NULL,
  regularizada_por_usuario_id BIGINT NULL REFERENCES usuarios(id),
  regularizada_at TIMESTAMP NULL,
  revocada_por_usuario_id BIGINT NULL REFERENCES usuarios(id),
  revocada_at TIMESTAMP NULL,
  motivo_revocacion TEXT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_contrato_excepciones_estado CHECK (
    estado IN ('ABIERTA', 'REGULARIZADA', 'VENCIDA', 'REVOCADA')
  )
);

CREATE INDEX IF NOT EXISTS idx_contrato_excepciones_contrato
  ON contrato_excepciones_documentales (contrato_id, estado, fecha_limite_regularizacion);

ALTER TABLE alertas_documentales
  DROP CONSTRAINT IF EXISTS chk_alertas_documentales_tipo_alerta;

ALTER TABLE alertas_documentales
  ADD CONSTRAINT chk_alertas_documentales_tipo_alerta CHECK (
    tipo_alerta IN (
      'DOCUMENTO_FALTANTE',
      'DOCUMENTO_VENCIDO',
      'DOCUMENTO_POR_VENCER',
      'EXPEDIENTE_INCOMPLETO',
      'DOCUMENTO_DEVUELTO',
      'REQUISITO_CRITICO_PENDIENTE',
      'EXCEPCION_POR_VENCER',
      'EXCEPCION_VENCIDA',
      'CONTRATO_SUSPENDIDO',
      'CONTRATO_POR_VENCER',
      'CONTRATO_SIN_ACTA_INICIO',
      'EVENTO_SIN_SOPORTE'
    )
  );
