CREATE TABLE IF NOT EXISTS agenda_tareas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresas(id),
  titulo TEXT NOT NULL CHECK (length(btrim(titulo)) BETWEEN 1 AND 240),
  descripcion TEXT,
  tipo TEXT NOT NULL CHECK (tipo IN ('TALENTO_HUMANO','COBERTURA','NOMINA','DOCUMENTOS','SST','REMISIONES','CONTRATOS','ADMINISTRATIVA','OTRA')),
  prioridad TEXT NOT NULL DEFAULT 'C' CHECK (prioridad IN ('A','B','C')),
  estado TEXT NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','EN_PROCESO','TERMINADA','REPROGRAMADA','CANCELADA')),
  fecha_prevista DATE NOT NULL,
  hora_inicio TIME,
  hora_finalizacion TIME,
  duracion_estimada_minutos INTEGER CHECK (duracion_estimada_minutos IS NULL OR duracion_estimada_minutos > 0),
  fecha_limite DATE,
  responsable_id BIGINT NOT NULL REFERENCES usuarios(id),
  creador_id BIGINT NOT NULL REFERENCES usuarios(id),
  origen TEXT NOT NULL DEFAULT 'MANUAL' CHECK (origen IN ('MANUAL','MODULO','SISTEMA')),
  modulo_relacionado TEXT CHECK (modulo_relacionado IS NULL OR modulo_relacionado IN ('PERSONAL','COBERTURA','NOMINA','DOCUMENTOS','SST','REMISIONES','CONTRATOS','ADMINISTRACION')),
  tipo_entidad_relacionada TEXT CHECK (tipo_entidad_relacionada IS NULL OR tipo_entidad_relacionada IN ('PERSONA','VINCULACION','CONTRATO','PERIODO','DOCUMENTO','REMISION','CASO_SST','INSTITUCION','SEDE')),
  entidad_relacionada_id BIGINT,
  municipio_id BIGINT REFERENCES municipios(id),
  institucion_id BIGINT REFERENCES instituciones(id),
  sede_id BIGINT REFERENCES sedes(id),
  persona_id BIGINT REFERENCES personas(id),
  vinculacion_id BIGINT REFERENCES vinculaciones(id),
  requiere_seguimiento BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_proxima_seguimiento DATE,
  motivo_cancelacion TEXT,
  motivo_reprogramacion TEXT,
  fecha_terminacion DATE,
  version INTEGER NOT NULL DEFAULT 1,
  archivada BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (fecha_limite IS NULL OR fecha_limite >= fecha_prevista),
  CHECK (estado <> 'TERMINADA' OR fecha_terminacion IS NOT NULL),
  CHECK (estado <> 'CANCELADA' OR length(btrim(COALESCE(motivo_cancelacion,''))) >= 3),
  CHECK (estado <> 'REPROGRAMADA' OR length(btrim(COALESCE(motivo_reprogramacion,''))) >= 3),
  CHECK ((modulo_relacionado IS NULL) = (tipo_entidad_relacionada IS NULL AND entidad_relacionada_id IS NULL))
);

CREATE TABLE IF NOT EXISTS agenda_tarea_participantes (
  tarea_id BIGINT NOT NULL REFERENCES agenda_tareas(id) ON DELETE CASCADE,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (tarea_id, usuario_id)
);

CREATE TABLE IF NOT EXISTS agenda_tarea_asignaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresas(id), tarea_id BIGINT NOT NULL REFERENCES agenda_tareas(id) ON DELETE CASCADE,
  responsable_anterior_id BIGINT REFERENCES usuarios(id), responsable_nuevo_id BIGINT NOT NULL REFERENCES usuarios(id),
  asignado_por_id BIGINT NOT NULL REFERENCES usuarios(id), motivo TEXT, fecha_asignacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agenda_tarea_seguimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresas(id), tarea_id BIGINT NOT NULL REFERENCES agenda_tareas(id) ON DELETE CASCADE,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id), tipo TEXT NOT NULL CHECK (tipo IN ('COMENTARIO','CAMBIO_ESTADO','EVIDENCIA','REPROGRAMACION','REASIGNACION','CIERRE','REAPERTURA')),
  comentario TEXT, estado_anterior TEXT, estado_nuevo TEXT, fecha_anterior DATE, fecha_nueva DATE, evidencia_documento_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS agenda_top_tareas (
  empresa_id BIGINT NOT NULL REFERENCES empresas(id), usuario_id BIGINT NOT NULL REFERENCES usuarios(id), fecha DATE NOT NULL,
  tarea_id BIGINT NOT NULL REFERENCES agenda_tareas(id) ON DELETE CASCADE, posicion SMALLINT NOT NULL CHECK (posicion BETWEEN 1 AND 3),
  PRIMARY KEY (empresa_id, usuario_id, fecha, posicion), UNIQUE (empresa_id, usuario_id, fecha, tarea_id)
);

CREATE TABLE IF NOT EXISTS agenda_cierres_diarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL REFERENCES empresas(id), usuario_id BIGINT NOT NULL REFERENCES usuarios(id), fecha DATE NOT NULL,
  resumen TEXT, terminadas TEXT, pendientes TEXT, reprogramadas TEXT, observaciones TEXT, version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE (empresa_id, usuario_id, fecha)
);

CREATE INDEX IF NOT EXISTS idx_agenda_tareas_empresa_fecha ON agenda_tareas(empresa_id, fecha_prevista, estado, archivada);
CREATE INDEX IF NOT EXISTS idx_agenda_tareas_responsable ON agenda_tareas(empresa_id, responsable_id, fecha_prevista);
CREATE INDEX IF NOT EXISTS idx_agenda_seguimientos_tarea ON agenda_tarea_seguimientos(empresa_id, tarea_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agenda_top_fecha ON agenda_top_tareas(empresa_id, usuario_id, fecha);
