-- Fase 36: base operativa SIMAT. No modifica tablas ni reglas económicas de nómina.
ALTER TABLE IF EXISTS instituciones ADD COLUMN IF NOT EXISTS etc text, ADD COLUMN IF NOT EXISTS jerarquia text, ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT 'ACTIVO';
ALTER TABLE IF EXISTS sedes ADD COLUMN IF NOT EXISTS zona_sede text, ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT 'ACTIVO', ADD COLUMN IF NOT EXISTS vigente_desde date, ADD COLUMN IF NOT EXISTS vigente_hasta date, ADD COLUMN IF NOT EXISTS updated_at timestamp NOT NULL DEFAULT now();
-- Aplicar únicamente mediante el proceso de migraciones del ambiente destino.
CREATE TABLE IF NOT EXISTS operacion_simat_importaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES empresas(id),
  contrato_id bigint NULL REFERENCES contratos(id),
  nombre_archivo text NOT NULL,
  estado text NOT NULL DEFAULT 'PENDIENTE_CONFIRMACION' CHECK (estado IN ('PENDIENTE_CONFIRMACION','CONFIRMADA','RECHAZADA','ERROR')),
  encabezados jsonb NOT NULL DEFAULT '[]'::jsonb,
  resumen jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by bigint NULL REFERENCES usuarios(id),
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_operacion_simat_import_empresa ON operacion_simat_importaciones(empresa_id, created_at DESC);

CREATE TABLE IF NOT EXISTS operacion_simat_registros (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  importacion_id bigint NOT NULL REFERENCES operacion_simat_importaciones(id) ON DELETE CASCADE,
  empresa_id bigint NOT NULL REFERENCES empresas(id), contrato_id bigint NULL REFERENCES contratos(id),
  institucion_id bigint NULL REFERENCES instituciones(id), sede_id bigint NULL REFERENCES sedes(id),
  ano integer, etc text, estado text, jerarquia text, institucion text, dane text, sede text, codigo_dane_sede text,
  consecutivo text, zona_sede text, jornada text, grado_cod text, grupo text, renombre text, modelo text,
  fechaini date, estrato text, sisben_iv text, per_id text, doc text, tipodoc text, apellido1 text, apellido2 text,
  nombre1 text, nombre2 text, genero text, fecha_nacimiento date, barrio text, eps text, tipo_sangre text,
  matricula_contratada text, fuente_recursos text, internado text, num_contrato text, ha_estado_vinculado_srpa text,
  esta_activo_srpa text, discapacidad text, pais_origen text, correo text, telefono text, etnia text,
  tra_esp_apr_escolar text, apoyo_academico_especial text, list_cap_excepcionales text, campesino text,
  pais_nacimiento text, pais_nacionalidad2 text, categoria_aula text, grupo_etario text, focalizacion text, complemento text,
  source_row integer NOT NULL, source_data jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamp NOT NULL DEFAULT now(), updated_at timestamp NOT NULL DEFAULT now(),
  UNIQUE(importacion_id, source_row)
);
CREATE INDEX IF NOT EXISTS idx_operacion_simat_registros_tenant ON operacion_simat_registros(empresa_id, ano, doc);
CREATE INDEX IF NOT EXISTS idx_operacion_simat_registros_sede ON operacion_simat_registros(sede_id, ano);
CREATE INDEX IF NOT EXISTS idx_operacion_simat_registros_filtros ON operacion_simat_registros(empresa_id, institucion_id, sede_id, jornada, focalizacion);
CREATE UNIQUE INDEX IF NOT EXISTS uq_operacion_simat_estudiante_ano ON operacion_simat_registros(empresa_id, ano, (COALESCE(NULLIF(per_id,''), NULLIF(doc,'')))) WHERE COALESCE(NULLIF(per_id,''), NULLIF(doc,'')) IS NOT NULL;
