create table if not exists public.alertas_documentales (
  id bigint generated by default as identity primary key,
  empresa_id bigint references public.empresas(id),
  contrato_id bigint references public.contratos(id),
  vinculacion_id bigint references public.vinculaciones(id),
  persona_id bigint references public.personas(id),
  tipo_documento_id bigint references public.tipos_documentos(id),
  tipo_alerta text not null,
  severidad text not null,
  estado text not null default 'ACTIVA',
  titulo text not null,
  descripcion text,
  fecha_alerta date default current_date,
  fecha_vencimiento date,
  dias_restantes integer,
  activo boolean default true,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  constraint chk_alertas_documentales_tipo_alerta check (
    tipo_alerta in (
      'DOCUMENTO_FALTANTE',
      'DOCUMENTO_VENCIDO',
      'DOCUMENTO_POR_VENCER',
      'EXPEDIENTE_INCOMPLETO'
    )
  ),
  constraint chk_alertas_documentales_severidad check (
    severidad in ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')
  ),
  constraint chk_alertas_documentales_estado check (
    estado in ('ACTIVA', 'RESUELTA', 'IGNORADA')
  )
);

create index if not exists idx_alertas_documentales_empresa_id
  on public.alertas_documentales (empresa_id);

create index if not exists idx_alertas_documentales_contrato_id
  on public.alertas_documentales (contrato_id);

create index if not exists idx_alertas_documentales_vinculacion_id
  on public.alertas_documentales (vinculacion_id);

create index if not exists idx_alertas_documentales_persona_id
  on public.alertas_documentales (persona_id);

create index if not exists idx_alertas_documentales_tipo_alerta
  on public.alertas_documentales (tipo_alerta);

create index if not exists idx_alertas_documentales_severidad
  on public.alertas_documentales (severidad);

create index if not exists idx_alertas_documentales_estado
  on public.alertas_documentales (estado);

create index if not exists idx_alertas_documentales_fecha_vencimiento
  on public.alertas_documentales (fecha_vencimiento);
