ALTER TABLE agenda_cierres_diarios ADD COLUMN IF NOT EXISTS resumen_dia TEXT;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uq_agenda_cierres_id_empresa') THEN
    ALTER TABLE agenda_cierres_diarios ADD CONSTRAINT uq_agenda_cierres_id_empresa UNIQUE (id, empresa_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='uq_agenda_tareas_id_empresa') THEN
    ALTER TABLE agenda_tareas ADD CONSTRAINT uq_agenda_tareas_id_empresa UNIQUE (id, empresa_id);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS agenda_cierre_tareas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL,
  cierre_id BIGINT NOT NULL,
  tarea_id BIGINT NOT NULL,
  clasificacion TEXT NOT NULL CHECK (clasificacion IN ('TERMINADA','PENDIENTE','REPROGRAMADA')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_agenda_cierre_tareas_cierre FOREIGN KEY (cierre_id, empresa_id) REFERENCES agenda_cierres_diarios(id, empresa_id) ON DELETE CASCADE,
  CONSTRAINT fk_agenda_cierre_tareas_tarea FOREIGN KEY (tarea_id, empresa_id) REFERENCES agenda_tareas(id, empresa_id) ON DELETE CASCADE,
  CONSTRAINT uq_agenda_cierre_tarea_clasificacion UNIQUE (cierre_id, tarea_id, clasificacion)
);

CREATE INDEX IF NOT EXISTS idx_agenda_cierre_tareas_cierre ON agenda_cierre_tareas(empresa_id, cierre_id);
CREATE INDEX IF NOT EXISTS idx_agenda_cierre_tareas_tarea ON agenda_cierre_tareas(empresa_id, tarea_id);
