-- Integracion fase 1: outbox transaccional y observacion de impactos.
-- Idempotente. No modifica datos operativos existentes.

BEGIN;

CREATE TABLE IF NOT EXISTS public.integracion_eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id TEXT NOT NULL,
  empresa_id BIGINT NULL REFERENCES public.empresas(id),
  contrato_id BIGINT NULL REFERENCES public.contratos(id),
  persona_id BIGINT NULL REFERENCES public.personas(id),
  vinculacion_id BIGINT NULL REFERENCES public.vinculaciones(id),
  effective_date DATE NOT NULL,
  periodo_id BIGINT NULL REFERENCES public.nomina_periodos(id),
  payload_before JSONB NULL,
  payload_after JSONB NULL,
  idempotency_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDIENTE',
  attempts INTEGER NOT NULL DEFAULT 0,
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  locked_at TIMESTAMPTZ NULL,
  locked_by TEXT NULL,
  processed_at TIMESTAMPTZ NULL,
  last_error_code TEXT NULL,
  last_error_message TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_integracion_eventos_idempotency UNIQUE (idempotency_key),
  CONSTRAINT chk_integracion_eventos_status CHECK (status IN ('PENDIENTE','PROCESANDO','PROCESADO','ERROR')),
  CONSTRAINT chk_integracion_eventos_attempts CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS idx_integracion_eventos_claim
  ON public.integracion_eventos (status, available_at, id);
CREATE INDEX IF NOT EXISTS idx_integracion_eventos_empresa_contrato
  ON public.integracion_eventos (empresa_id, contrato_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_integracion_eventos_vinculacion
  ON public.integracion_eventos (vinculacion_id, effective_date, id);
CREATE INDEX IF NOT EXISTS idx_integracion_eventos_persona
  ON public.integracion_eventos (persona_id, effective_date, id);
CREATE INDEX IF NOT EXISTS idx_integracion_eventos_periodo
  ON public.integracion_eventos (periodo_id, id);
CREATE INDEX IF NOT EXISTS idx_integracion_eventos_effective_date
  ON public.integracion_eventos (effective_date, id);

CREATE TABLE IF NOT EXISTS public.integracion_evento_impactos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id BIGINT NOT NULL REFERENCES public.integracion_eventos(id) ON DELETE CASCADE,
  periodo_id BIGINT NULL REFERENCES public.nomina_periodos(id),
  vinculacion_id BIGINT NOT NULL REFERENCES public.vinculaciones(id),
  fecha_desde DATE NOT NULL,
  fecha_hasta DATE NOT NULL,
  periodo_estado TEXT NOT NULL,
  accion_requerida TEXT NOT NULL,
  requiere_recalculo BOOLEAN NOT NULL DEFAULT FALSE,
  bloqueado_por_cierre BOOLEAN NOT NULL DEFAULT FALSE,
  contexto_antes JSONB NULL,
  contexto_despues JSONB NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_integracion_evento_impacto UNIQUE (evento_id, periodo_id, vinculacion_id, fecha_desde, fecha_hasta),
  CONSTRAINT chk_integracion_evento_impacto_accion CHECK (accion_requerida IN ('REQUIERE_SINCRONIZACION','REQUIERE_AJUSTE_AUTORIZADO','SIN_IMPACTO')),
  CONSTRAINT chk_integracion_evento_impacto_rango CHECK (fecha_hasta >= fecha_desde)
);

CREATE INDEX IF NOT EXISTS idx_integracion_impactos_periodo
  ON public.integracion_evento_impactos (periodo_id, periodo_estado, accion_requerida);
CREATE INDEX IF NOT EXISTS idx_integracion_impactos_vinculacion
  ON public.integracion_evento_impactos (vinculacion_id, fecha_desde, fecha_hasta);

COMMIT;

COMMENT ON TABLE public.integracion_eventos IS 'Outbox transaccional para cambios canónicos de Personal y Nómina.';
COMMENT ON TABLE public.integracion_evento_impactos IS 'Impactos observados por periodo; no muta Planilla ni Nómina en fase 1.';
