CREATE TABLE IF NOT EXISTS usuario_empresas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint NOT NULL REFERENCES usuarios(id),
  empresa_id bigint NOT NULL REFERENCES empresas(id),
  activo boolean DEFAULT TRUE,
  created_at timestamp DEFAULT NOW(),
  CONSTRAINT usuario_empresas_usuario_id_empresa_id_key UNIQUE (usuario_id, empresa_id)
);

CREATE TABLE IF NOT EXISTS usuario_contratos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id bigint NOT NULL REFERENCES usuarios(id),
  contrato_id bigint NOT NULL REFERENCES contratos(id),
  activo boolean DEFAULT TRUE,
  created_at timestamp DEFAULT NOW(),
  CONSTRAINT usuario_contratos_usuario_id_contrato_id_key UNIQUE (usuario_id, contrato_id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_empresas_usuario_id
  ON usuario_empresas (usuario_id);

CREATE INDEX IF NOT EXISTS idx_usuario_empresas_empresa_id
  ON usuario_empresas (empresa_id);

CREATE INDEX IF NOT EXISTS idx_usuario_contratos_usuario_id
  ON usuario_contratos (usuario_id);

CREATE INDEX IF NOT EXISTS idx_usuario_contratos_contrato_id
  ON usuario_contratos (contrato_id);
