-- ADMIN-2C: configuración empresarial tipada y parámetros económicos históricos.
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TABLE IF NOT EXISTS empresa_configuracion_general (
 empresa_id BIGINT PRIMARY KEY REFERENCES empresas(id) ON DELETE CASCADE,
 nombre_comercial VARCHAR(180), dv VARCHAR(2), pais VARCHAR(80) NOT NULL DEFAULT 'Colombia',
 zona_horaria VARCHAR(80) NOT NULL DEFAULT 'America/Bogota', moneda CHAR(3) NOT NULL DEFAULT 'COP',
 locale VARCHAR(20) NOT NULL DEFAULT 'es-CO', logo_url TEXT, encabezado_documentos TEXT,
 updated_by BIGINT REFERENCES usuarios(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 CONSTRAINT ck_empresa_config_moneda CHECK(moneda ~ '^[A-Z]{3}$'),
 CONSTRAINT ck_empresa_config_dv CHECK(dv IS NULL OR dv ~ '^[0-9]{1,2}$')
);
CREATE TABLE IF NOT EXISTS empresa_modulo_configuracion (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, empresa_id BIGINT NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
 modulo_id BIGINT NOT NULL REFERENCES modulos(id) ON DELETE RESTRICT, estado VARCHAR(24) NOT NULL DEFAULT 'PENDIENTE',
 observaciones TEXT, updated_by BIGINT REFERENCES usuarios(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 CONSTRAINT uq_empresa_modulo_config UNIQUE(empresa_id,modulo_id),
 CONSTRAINT ck_empresa_modulo_config_estado CHECK(estado IN('PENDIENTE','INCOMPLETA','CONFIGURADA'))
);
CREATE INDEX IF NOT EXISTS idx_empresa_modulo_config_empresa ON empresa_modulo_configuracion(empresa_id);
CREATE TABLE IF NOT EXISTS nomina_parametros_economicos (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, empresa_id BIGINT NOT NULL REFERENCES empresas(id) ON DELETE RESTRICT,
 vigente_desde DATE NOT NULL, vigente_hasta DATE, salario_minimo NUMERIC(16,2), auxilio_transporte NUMERIC(16,2), uvt NUMERIC(16,2),
 porcentaje_salud_empleado NUMERIC(8,6), porcentaje_pension_empleado NUMERIC(8,6), porcentaje_fondo_solidaridad NUMERIC(8,6),
 porcentaje_hora_extra_diurna NUMERIC(8,6), porcentaje_hora_extra_nocturna NUMERIC(8,6), porcentaje_recargo_nocturno NUMERIC(8,6),
 regla_redondeo VARCHAR(20) NOT NULL DEFAULT 'NEAREST', observaciones TEXT, created_by BIGINT REFERENCES usuarios(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 CONSTRAINT ck_nomina_parametros_vigencia CHECK(vigente_hasta IS NULL OR vigente_hasta>=vigente_desde),
 CONSTRAINT ck_nomina_parametros_redondeo CHECK(regla_redondeo IN('NEAREST','FLOOR','CEIL','NONE')),
 CONSTRAINT ck_nomina_parametros_valores CHECK(COALESCE(salario_minimo,0)>=0 AND COALESCE(auxilio_transporte,0)>=0 AND COALESCE(uvt,0)>=0)
);
CREATE INDEX IF NOT EXISTS idx_nomina_parametros_empresa_fecha ON nomina_parametros_economicos(empresa_id,vigente_desde DESC);
DO $$ BEGIN ALTER TABLE nomina_parametros_economicos ADD CONSTRAINT ex_nomina_parametros_sin_solape EXCLUDE USING gist
 (empresa_id WITH =, daterange(vigente_desde,COALESCE(vigente_hasta,'infinity'::date),'[]') WITH &&);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
