-- Phase 15: Configuración de Calculadoras
-- Tables for salary and personnel calculator configuration with versioning and audit

-- ─── Salary Calculator Config ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS calculadora_salario_config (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version          integer      NOT NULL DEFAULT 1,
  nombre           varchar(120) NOT NULL,
  descripcion      text,

  -- Salary parameters
  salario_base_tc  numeric(14, 2) NOT NULL DEFAULT 1423500,
  salario_base_mt  numeric(14, 2) NOT NULL DEFAULT 711750,
  salario_base_ops numeric(14, 2) NOT NULL DEFAULT 1650000,
  auxilio_transporte numeric(14, 2) NOT NULL DEFAULT 200000,

  -- Deduction percentages (stored as decimal, e.g. 0.04 = 4%)
  porcentaje_salud   numeric(8, 6) NOT NULL DEFAULT 0.04,
  porcentaje_pension numeric(8, 6) NOT NULL DEFAULT 0.04,

  -- Surcharge
  recargo_horas_extra numeric(8, 6) NOT NULL DEFAULT 0.25,
  dias_mes            integer NOT NULL DEFAULT 30,

  -- Formula
  formula_neto         text   NOT NULL DEFAULT 'salario_base + auxilio_transporte + adiciones + recargos - salud - pension - deducciones',
  variables_permitidas text[] NOT NULL DEFAULT ARRAY['salario_base','auxilio_transporte','adiciones','recargos','salud','pension','deducciones','devengado'],
  regla_redondeo       varchar(20) NOT NULL DEFAULT 'nearest',

  -- Versioning
  config_padre_id  bigint REFERENCES calculadora_salario_config(id),
  vigencia_desde   date NOT NULL DEFAULT CURRENT_DATE,
  vigencia_hasta   date,
  estado           varchar(20) NOT NULL DEFAULT 'activo'
                   CHECK (estado IN ('activo','inactivo')),
  observacion_cambio text,

  -- Audit
  usuario_creacion     bigint NOT NULL REFERENCES usuarios(id),
  usuario_modificacion bigint REFERENCES usuarios(id),
  creado_en            timestamp NOT NULL DEFAULT NOW(),
  modificado_en        timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_calc_salario_estado    ON calculadora_salario_config(estado);
CREATE INDEX IF NOT EXISTS idx_calc_salario_vigencia  ON calculadora_salario_config(vigencia_desde, vigencia_hasta);
CREATE INDEX IF NOT EXISTS idx_calc_salario_version   ON calculadora_salario_config(config_padre_id);

-- ─── Personnel Calculator Config ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS calculadora_personal_config (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version     integer      NOT NULL DEFAULT 1,
  nombre      varchar(120) NOT NULL,
  descripcion text,

  -- Method: formula | rangos
  metodo   varchar(20) NOT NULL DEFAULT 'rangos'
           CHECK (metodo IN ('formula','rangos')),

  -- Scope (null = applies to all)
  modalidad varchar(50),

  -- Formula fields (used when metodo = 'formula')
  formula              text,
  variables_permitidas text[] NOT NULL DEFAULT ARRAY['cupos','base','minimo','divisor','modalidad','contrato_id'],

  -- Shared
  personal_minimo  integer NOT NULL DEFAULT 0,
  personal_maximo  integer,
  regla_redondeo   varchar(20) NOT NULL DEFAULT 'ceil'
                   CHECK (regla_redondeo IN ('nearest','floor','ceil','none')),

  -- Versioning
  config_padre_id  bigint REFERENCES calculadora_personal_config(id),
  vigencia_desde   date NOT NULL DEFAULT CURRENT_DATE,
  vigencia_hasta   date,
  estado           varchar(20) NOT NULL DEFAULT 'activo'
                   CHECK (estado IN ('activo','inactivo')),
  observacion_cambio text,

  -- Audit
  usuario_creacion     bigint NOT NULL REFERENCES usuarios(id),
  usuario_modificacion bigint REFERENCES usuarios(id),
  creado_en            timestamp NOT NULL DEFAULT NOW(),
  modificado_en        timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_calc_personal_estado    ON calculadora_personal_config(estado);
CREATE INDEX IF NOT EXISTS idx_calc_personal_modalidad ON calculadora_personal_config(modalidad);
CREATE INDEX IF NOT EXISTS idx_calc_personal_vigencia  ON calculadora_personal_config(vigencia_desde, vigencia_hasta);

-- ─── Personnel Calculator Ranges ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS calculadora_personal_rangos (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_id          bigint NOT NULL REFERENCES calculadora_personal_config(id) ON DELETE CASCADE,
  desde              integer NOT NULL,
  hasta              integer,          -- NULL = "en adelante" (infinity)
  personal_requerido integer NOT NULL,
  orden              integer NOT NULL DEFAULT 0,
  estado             varchar(20) NOT NULL DEFAULT 'activo'
                     CHECK (estado IN ('activo','inactivo')),
  creado_en          timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_calc_rangos_config_id ON calculadora_personal_rangos(config_id);
CREATE INDEX IF NOT EXISTS idx_calc_rangos_estado    ON calculadora_personal_rangos(estado, config_id);

-- ─── Constraint: Only one active config per modalidad at a time ──────────────

CREATE UNIQUE INDEX IF NOT EXISTS uq_calc_personal_activo_modalidad
  ON calculadora_personal_config(modalidad, estado)
  WHERE estado = 'activo';

CREATE UNIQUE INDEX IF NOT EXISTS uq_calc_salario_activo
  ON calculadora_salario_config(estado)
  WHERE estado = 'activo';
